In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv(r'datasets/3.4 Wty_Claims_data_new.csv')#file location
df[:5]

,Refno Claim,Claim Registration Date,Repair Date,Repairing Dealer,State,Job Number,Vehicle Marketing Type,Product Id,Causal Part Number,Causal Part Name,...,Total Other Payment Local,Total Payment Local,Total_Payment,Company,Delivery Importer,Credit Date,Debit Code,Credit Period,Model_,Year
0,7982280,NaN,10/08/2015,490233.0,QLD,1.0,FH13 64T,NaN,85003217,"CYLINDER HEAD, EXCH, SPARE PART",...,0.0,7370.01,7370.01,NaN,NaN,42250,9,42248,FH13,2015
1,133058,NaN,27/08/2015,93385.0,NSW,1.0,FH13 64T,NaN,20538793,"SEALING STRIP, VALVE COVER",...,0.0,173.22,173.22,NaN,NaN,42250,9,42248,FH13,2015
2,7982526,NaN,12/08/2015,79129.0,VIC,2.0,FH13 64T,NaN,20910962,"EXHAUST MANIFOLD, FRONT AND REAR",...,160.0,509.62,509.62,#DIV/0!,NaN,42250,9,42248,FH13,2015
3,1202209,NaN,28/08/2015,691188.0,SA,1.0,FH13 64T,NaN,21351717,"INJECTOR SLEEVE, SPARE PART KIT",...,0.0,1864.20,1864.20,3.185125,NaN,42250,9,42248,FH13,2015
4,130161,NaN,28/08/2015,92767.0,WA,2.0,FH13 64T,NaN,21368390,"OIL PAN, PLASTIC",...,0.0,2246.32,2246.32,#DIV/0!,NaN,42250,9,42248,FH13,2015

In [2]:
#6.循环的3种方法

In [3]:
#第一种
rc = len(df.index)
rc

24379

In [4]:
for n in range(rc):
    print(df['State'][n])

QLD
NSW
VIC
SA
WA
WA
NSW
QLD
NSW
NSW
VIC
SA
WA
NSW
NSW
QLD
WA
QLD
SA
NSW
WA
QLD
QLD
VIC
VIC
SA
WA
WA
VIC
WA
WA
TA
WA
QLD
WA
WA
QLD
WA
QLD
WA
WA
WA
WA
NSW
NSW
SA
WA
VIC
VIC
VIC
QLD
WA
WA
SA
SA
SA
SA
WA
WA
WA
WA
WA
VIC
VIC
VIC
SA
SA
NSW
NSW
NSW
WA
VIC
VIC
VIC
NSW
NSW
NSW
NSW
NSW
NSW
SA
SA
SA
SA
SA
NSW
NSW
NSW
WA
WA
NSW
SA
SA
VIC
QLD
QLD
QLD
SA
SA
SA
QLD
SA
SA
VIC
VIC
QLD
WA
WA
NSW
NSW
NSW
NSW
VIC
VIC
WA
WA
WA
WA
WA
WA
NSW
VIC
VIC
VIC
QLD
WA
QLD
NSW
QLD
QLD
SA
WA
NSW
NSW
SA
VIC
WA
SA
SA
SA
WA
SA
NSW
SA
SA
SA
SA
SA
SA
NSW
QLD
WA
WA
WA
WA
WA
NSW
NSW
NSW
NSW
SA
WA
TA
TA
WA
WA
WA
VIC
SA
SA
WA
WA
WA
WA
VIC
NSW
VIC
SA
SA
WA
SA
NSW
WA
WA
WA
VIC
VIC
VIC
SA
NSW
QLD
SA
VIC
VIC
NSW
NSW
NSW
QLD
SA
WA
NSW
NSW
WA
QLD
WA
WA
SA
SA
SA
NSW
NSW
NSW
WA
NSW
NSW
QLD
NSW
NSW
NSW
WA
WA
WA
VIC
VIC
QLD
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
NSW
NSW
WA
SA
WA
WA
NSW
NSW
SA
NSW
QLD
QLD
QLD
WA
WA
WA
WA
WA
WA
WA
WA
QLD
QLD
SA
WA
WA
QLD
QLD
QLD
QLD
QLD
WA
QLD
WA
WA
QLD
NSW
NSW
SA
WA
SA
WA
WA
WA
WA
WA
NSW
NSW
WA
WA
WA
VIC
NSW
NSW
QLD
VIC
SA
SA
SA
SA
NSW
NSW
SA
SA
SA
SA
NSW
SA
SA
NSW
WA
WA
SA
QLD
NSW
NSW
NSW
NSW
WA
WA
WA
WA
WA
WA
VIC
VIC
VIC
VIC
VIC
VIC
SA
WA
SA
NSW
NSW
NSW
SA
SA
NSW
NSW
SA
NSW
NSW
WA
VIC
SA
SA
SA
SA
SA
SA
NSW
SA
SA
SA
SA
SA
SA
SA
SA
SA
WA
WA
SA
WA
WA
WA
WA
WA
SA
SA
NSW
SA
NSW
WA
WA
WA
WA
WA
QLD
WA
SA
QLD
TA
WA
SA
SA
NSW
QLD
QLD
QLD
WA
QLD
QLD
WA
TA
QLD
QLD
QLD
QLD
QLD
QLD
VIC
VIC
VIC
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
NSW
NSW
NSW
NSW
QLD
VIC
VIC
VIC
VIC
WA
WA
VIC
VIC
VIC
WA
WA
WA
NSW
NSW
NSW
NSW
SA
VIC
VIC
SA
SA
QLD
WA
WA
WA
QLD
VIC
WA
SA
SA
NSW
NSW
SA
VIC
SA
SA
VIC
NSW
SA
SA
SA
SA
SA
SA
WA
WA
WA
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
NSW
QLD
QLD
QLD
QLD
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
SA
SA
QLD
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
QLD
QLD
QLD
QLD
QLD
VIC
VIC
VIC
QLD
QLD
QLD
QLD
QLD
QLD
QLD
WA
WA
WA
WA
NSW
WA
WA
NSW
NSW
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
VIC
VIC
VIC
QLD
QLD
QLD
QLD
WA
NSW
QLD
QLD
QLD
WA
SA
VIC
NSW
SA
VIC
VIC
WA
NSW
WA
NSW
NSW
NSW
NSW
SA
SA
SA
SA
WA
VIC
SA
SA
WA
WA
WA
VIC
WA
SA
SA
SA
SA
SA
SA
SA
NSW
SA
NSW
NSW
NSW
QLD
VIC
VIC
VIC
VIC
WA
WA
QLD
NSW
VIC
VIC
VIC
WA
SA
SA
SA
QLD
QLD
SA
NSW
WA
SA
SA
QLD
QLD
NSW
NSW
NSW
SA
SA
SA
SA
VIC
QLD
QLD
SA
SA
SA
SA
SA
NSW
NSW
QLD
WA
SA
WA
WA
WA
SA
WA
WA
QLD
QLD
QLD
QLD
VIC
VIC
SA
SA
WA
VIC
SA
NSW
NSW
WA
QLD
WA
SA
SA
QLD
SA
NSW
WA
QLD
WA
WA
WA
SA
WA
WA
WA
WA
SA
VIC
SA
WA
VIC
SA
NSW
SA
QLD
VIC
QLD
QLD
QLD
SA
QLD
QLD
QLD
QLD
QLD
WA
WA
VIC
WA
QLD
SA
QLD
QLD
SA
NSW
NSW
VIC
QLD
VIC
QLD
QLD
SA
SA
SA
SA
SA
NSW
QLD
QLD
QLD
QLD
QLD
QLD
SA
QLD
WA
QLD
SA
QLD
QLD
QLD
NSW
SA
NSW
NSW
NSW
WA
WA
WA
SA
VIC
VIC
WA
WA
VIC
QLD
NSW
NSW
SA
SA
SA
NSW
SA
SA
WA
SA
SA
SA
WA
WA
WA
SA
WA
WA
WA
WA
WA
WA
SA
SA
QLD
SA
WA
WA
WA
SA
SA
WA
WA
WA
WA
WA
SA
SA
WA
QLD
NSW
VIC
VIC
SA
SA
WA
WA
NSW
QLD
QLD
VIC
SA
WA
QLD
NSW
NSW
QLD
SA
WA
WA
WA
VIC
VIC
VIC
VIC
VIC
VIC
VIC
VIC
VIC
NSW
NSW
NSW
NSW
NSW
QLD
SA
SA
SA
QLD
SA
WA
WA
WA
WA
SA
SA
SA
SA
SA
QLD
WA
NSW
NSW
NSW
SA
SA
QLD
SA
SA
WA
QLD
QLD
QLD
QLD
WA
WA
VIC
WA
SA
NSW
WA
SA
NSW
QLD
QLD
WA
WA
WA
WA
SA
SA
WA
QLD
NSW
WA
VIC
SA
SA
WA
QLD
QLD
SA
NSW
SA
WA
NSW
NSW
SA
WA
NSW
NSW
NSW
WA
WA
WA
SA
SA
SA
WA
SA
SA
WA
NSW
NSW
NSW
WA
WA
SA
SA
QLD
WA
WA
WA
QLD
NSW
NSW
NSW
NSW
SA
QLD
WA
WA
WA
SA
SA
TA
WA
WA
NSW
NSW
WA
WA
WA
WA
SA
QLD
TA
WA
QLD
WA
WA
QLD
SA
SA
SA
QLD
WA
SA
NSW
WA
SA
SA
SA
VIC
VIC
WA
VIC
SA
TA
WA
NSW
SA
SA
QLD
SA
SA
SA
WA
TA
VIC
SA
NSW
NSW
SA
WA
WA
WA
WA
WA
WA
SA
VIC
SA
SA
SA
SA
SA
NSW
WA
SA
SA
NSW
NSW
NSW
VIC
SA
SA
SA
SA
QLD
SA
VIC
SA
QLD
WA
VIC
VIC
SA
SA
VIC
VIC
WA
NSW
NSW
WA
WA
SA
SA
SA
SA
WA
SA
WA
WA
WA
WA
WA
WA
WA
QLD
QLD
QLD
SA
QLD
QLD
QLD
QLD
VIC
VIC
NSW
WA
WA
WA
WA
VIC
WA
WA
WA
WA
WA
SA
SA
QLD
VIC
WA
QLD
QLD
NSW
WA
WA
WA
WA
NSW
NSW
WA
SA
QLD
QLD
VIC
SA
SA
NSW
VIC
WA
NSW
QLD
WA
QLD
QLD
WA
QLD
NSW
SA
QLD
WA
WA
WA
SA
VIC
NSW
NSW
SA
SA
QLD
NSW
WA
QLD
QLD
VIC
NSW
WA
SA
SA
WA
SA
SA
SA
SA
SA
SA
SA
SA
VIC
VIC
VIC
QLD
QLD
WA
NSW
QLD
QLD
QLD
SA
WA
SA
SA
WA
NSW
WA
VIC
QLD
WA
QLD
QLD
SA
WA
WA
WA
WA
QLD
QLD
WA
WA
WA
NSW
NSW
NSW
WA
SA
VIC
VIC
VIC
SA
SA
WA
WA
SA
SA
SA
WA
SA
SA
VIC
SA
WA
WA
WA
WA
NSW
NSW
SA
QLD
SA
SA
SA
NSW
NSW
WA
SA
VIC
QLD
SA
WA
SA
WA
QLD
QLD
SA
WA
WA
WA
VIC
WA
VIC
NSW
NSW
NSW
NSW
SA
NSW
WA
SA
WA
WA
SA
SA
SA
NSW
WA
WA
WA
WA
WA
WA
WA
NSW
WA
VIC
SA
NSW
NSW
NSW
NSW
NSW
SA
SA
SA
SA
TA
VIC
QLD
VIC
VIC
VIC
NSW
NSW
NSW
NSW
NSW
NSW
NSW
SA
SA
WA
NSW
WA
QLD
NSW
SA
SA
SA
QLD
SA
SA
SA
SA
WA
WA
SA
QLD
QLD
VIC
VIC
QLD
QLD
QLD
SA
WA
VIC
VIC
VIC
QLD
NSW
NSW
NSW
NSW
QLD
QLD
WA
WA
WA
NSW
NSW
SA
SA
SA
SA
VIC
QLD
NSW
QLD
QLD
SA
WA
SA
VIC
VIC
SA
SA
VIC
NSW
SA
WA
NSW
QLD
WA
QLD
WA
WA
SA
SA
SA
SA
SA
SA
SA
QLD
WA
SA
SA
SA
SA
SA
SA
WA
SA
SA
SA
SA
WA
NSW
NSW
QLD
WA
WA
WA
WA
SA
NSW
WA
WA
WA
QLD
SA
SA
NSW
VIC
VIC
VIC
SA
SA
WA
VIC
VIC
WA
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
NSW
NSW
SA
SA
SA
QLD
VIC
VIC
NSW
NSW
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
WA
WA
QLD
WA
WA
SA
SA
NSW
SA
SA
VIC
SA
SA
QLD
VIC
VIC
NSW
SA
SA
WA
SA
SA
SA
SA
SA
NSW
QLD
WA
QLD
NSW
NSW
WA
WA
WA
NSW
NSW
NSW
WA
NSW
SA
SA
SA
SA
NSW
NSW
SA
SA
SA
WA
SA
SA
SA
SA
SA
SA
NSW
NSW
NSW
QLD
NSW
WA
WA
SA
SA
SA
WA
WA
QLD
NSW
SA
QLD
QLD
QLD
WA
WA
WA
WA
WA
WA
SA
SA
NSW
QLD
WA
VIC
NSW
WA
WA
WA
WA
WA
WA
QLD
QLD
SA
VIC
VIC
WA
SA
SA
NSW
SA
NSW
QLD
SA
WA
SA
SA
SA
WA
WA
SA
SA
SA
WA
WA
NSW
SA
SA
WA
WA
WA
SA
QLD
NSW
QLD
WA
WA
WA
WA
SA
SA
SA
SA
NSW
SA
SA
SA
QLD
NSW
WA
SA
SA
SA
WA
SA
SA
SA
SA
SA
SA
NSW
WA
SA
SA
SA
WA
WA
QLD
NSW
WA
WA
SA
SA
WA
SA
SA
NSW
SA
WA
SA
SA
WA
SA
QLD
QLD
QLD
WA
WA
NSW
SA
SA
SA
SA
WA
WA
SA
WA
QLD
WA
WA
SA
WA
NSW
NSW
SA
WA
VIC
SA
NSW
NSW
NSW
QLD
WA
SA
SA
NSW
SA
QLD
NSW
WA
QLD
WA
WA
WA
VIC
SA
SA
SA
WA
WA
QLD
QLD
SA
WA
SA
SA
SA
SA
QLD
NSW
NSW
SA
WA
WA
SA
SA
SA
SA
WA
WA
WA
SA
SA
SA
SA
SA
WA
WA
SA
NSW
SA
NSW
SA
SA
WA
WA
NSW
VIC
SA
SA
SA
WA
QLD
QLD
QLD
WA
WA
SA
WA
VIC
VIC
VIC
VIC
WA
SA
SA
SA
SA
SA
SA
NSW
NSW
NSW
NSW
SA
SA
WA
SA
QLD
QLD
QLD
QLD
QLD
WA
NSW
VIC
SA
SA
WA
WA
WA
WA
NSW
SA
NSW
QLD
SA
SA
WA
WA
WA
VIC
SA
NSW
NSW
VIC
SA
SA
QLD
QLD
NSW
WA
NSW
NSW
SA
SA
QLD
WA
SA
QLD
QLD
SA
QLD
WA
SA
WA
VIC
WA
QLD
WA
QLD
WA
WA
WA
WA
VIC
SA
NSW
SA
SA
SA
SA
SA
SA
SA
SA
WA
SA
WA
WA
NSW
WA
WA
QLD
SA
SA
SA
SA
WA
WA
QLD
WA
SA
WA
WA
NSW
SA
SA
WA
WA
NSW
SA
WA
WA
QLD
QLD
WA
QLD
WA
WA
WA
WA
VIC
WA
VIC
SA
SA
QLD
TA
SA
WA
SA
WA
QLD
SA
QLD
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
WA
WA
WA
WA
SA
SA
TA
SA
SA
QLD
SA
WA
QLD
NSW
WA
WA
VIC
WA
SA
SA
WA
WA
QLD
SA
SA
QLD
NSW
SA
WA
WA
SA
SA
NSW
WA
WA
SA
QLD
SA
SA
WA
WA
VIC
SA
SA
SA
SA
SA
WA
SA
QLD
NSW
VIC
SA
SA
VIC
VIC
VIC
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
NSW
NSW
NSW
VIC
WA
QLD
WA
WA
WA
WA
WA
WA
SA
SA
NSW
VIC
WA
SA
QLD
QLD
NSW
NSW
WA
WA
WA
NSW
NSW
WA
WA
SA
SA
SA
NSW
WA
SA
VIC
SA
VIC
WA
SA
SA
VIC
TA
WA
SA
SA
SA
SA
SA
SA
WA
NSW
NSW
NSW
WA
WA
WA
SA
SA
QLD
WA
WA
WA
SA
SA
WA
WA
WA
SA
SA
SA
TA
SA
SA
SA
SA
SA
VIC
WA
SA
SA
VIC
NSW
WA
VIC
SA
NSW
QLD
QLD
QLD
WA
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
VIC
NSW
VIC
VIC
QLD
SA
SA
SA
WA
WA
WA
WA
WA
WA
QLD
SA
SA
SA
SA
SA
WA
NSW
NSW
WA
VIC
VIC
SA
VIC
SA
SA
WA
WA
SA
SA
QLD
NSW
QLD
QLD
WA
VIC
VIC
SA
VIC
SA
SA
SA
SA
SA
SA
WA
NSW
NSW
NSW
SA
SA
SA
SA
NSW
WA
SA
SA
WA
WA
WA
WA
WA
WA
SA
NSW
VIC
QLD
SA
SA
VIC
QLD
QLD
SA
SA
SA
SA
SA
SA
WA
WA
WA
QLD
WA
WA
WA
WA
SA
SA
SA
NSW
NSW
WA
WA
VIC
WA
QLD
WA
WA
WA
WA
WA
WA
SA
QLD
SA
NSW
WA
WA
WA
WA
WA
WA
VIC
WA
TA
SA
WA
SA
WA
WA
QLD
VIC
QLD
NSW
SA
WA
WA
WA
WA
SA
WA
WA
WA
SA
TA
WA
WA
SA
SA
NSW
WA
WA
SA
WA
VIC
WA
WA
SA
SA
SA
SA
SA
QLD
QLD
NSW
WA
NSW
VIC
VIC
WA
WA
WA
VIC
SA
SA
SA
SA
NSW
WA
WA
WA
QLD
TA
SA
SA
WA
WA
NSW
QLD
NSW
WA
WA
WA
WA
WA
SA
SA
NSW
SA
SA
SA
VIC
SA
NSW
SA
SA
SA
WA
WA
WA
WA
SA
SA
WA
WA
QLD
QLD
SA
SA
SA
SA
QLD
QLD
SA
SA
SA
SA
NSW
SA
WA
QLD
TA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
WA
SA
WA
WA
VIC
SA
QLD
WA
VIC
WA
WA
WA
QLD
SA
VIC
WA
SA
SA
SA
WA
QLD
QLD
QLD
TA
WA
WA
SA
VIC
VIC
SA
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
QLD
NSW
WA
WA
WA
QLD
SA
SA
SA
WA
SA
WA
WA
NSW
WA
WA
NSW
QLD
WA
VIC
WA
SA
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
WA
NSW
NSW
NSW
SA
SA
WA
WA
SA
SA
VIC
WA
WA
WA
WA
WA
QLD
QLD
WA
SA
WA
WA
WA
SA
SA
WA
WA
SA
SA
QLD
QLD
NSW
NSW
NSW
QLD
QLD
SA
WA
SA
WA
TA
WA
SA
NSW
VIC
SA
NSW
QLD
QLD
NSW
WA
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
WA
WA
WA
NSW
SA
SA
SA
WA
WA
WA
NSW
WA
SA
SA
SA
SA
SA
SA
WA
WA
WA
WA
WA
WA
SA
WA
WA
NSW
NSW
WA
SA
VIC
VIC
WA
VIC
WA
SA
SA
SA
SA
WA
QLD
VIC
VIC
NSW
SA
SA
SA
SA
SA
SA
SA
WA
VIC
WA
WA
SA
WA
NSW
VIC
QLD
NSW
WA
WA
QLD
WA
VIC
WA
VIC
VIC
SA
VIC
QLD
SA
QLD
SA
NSW
NSW
WA
NSW
WA
SA
WA
WA
SA
WA
WA
WA
WA
WA
VIC
VIC
SA
WA
SA
WA
NSW
NSW
NSW
SA
QLD
SA
SA
QLD
SA
SA
WA
WA
WA
QLD
QLD
QLD
WA
NSW
SA
SA
NSW
SA
WA
WA
SA
SA
SA
WA
SA
WA
SA
QLD
QLD
VIC
NSW
SA
NSW
QLD
QLD
QLD
SA
NSW
WA
WA
WA
VIC
SA
WA
NSW
SA
WA
QLD
WA
SA
SA
WA
SA
SA
NSW
NSW
WA
WA
SA
SA
QLD
SA
NSW
WA
WA
VIC
WA
SA
WA
WA
WA
WA
VIC
QLD
QLD
WA
VIC
TA
SA
WA
VIC
WA
SA
WA
WA
WA
SA
NSW
QLD
SA
SA
SA
TA
QLD
SA
NSW
SA
SA
SA
SA
SA
SA
SA
WA
SA
SA
WA
SA
SA
SA
SA
SA
QLD
QLD
WA
QLD
QLD
QLD
WA
WA
WA
WA
SA
SA
WA
QLD
SA
TA
SA
SA
SA
NSW
WA
TA
QLD
SA
QLD
QLD
SA
TA
SA
SA
SA
SA
WA
WA
WA
WA
SA
SA
SA
SA
VIC
VIC
SA
SA
SA
SA
SA
SA
SA
SA
WA
SA
WA
SA
VIC
SA
WA
SA
SA
TA
QLD
QLD
SA
SA
QLD
QLD
QLD
QLD
QLD
WA
QLD
QLD
QLD
WA
WA
WA
VIC
QLD
QLD
QLD
QLD
SA
WA
SA
VIC
WA
SA
WA
WA
SA
SA
SA
SA
SA
SA
SA
WA
WA
WA
WA
WA
NSW
WA
SA
SA
SA
SA
SA
WA
WA
WA
QLD
SA
SA
SA
WA
WA
SA
SA
SA
SA
SA
SA
WA
WA
NSW
NSW
NSW
SA
SA
SA
QLD
WA
SA
SA
SA
WA
SA
WA
WA
VIC
VIC
VIC
SA
SA
SA
SA
QLD
SA
SA
WA
NSW
SA
SA
SA
SA
SA
SA
SA
WA
SA
WA
QLD
QLD
QLD
QLD
QLD
QLD
WA
VIC
VIC
QLD
QLD
QLD
SA
SA
VIC
WA
WA
WA
SA
WA
WA
WA
SA
SA
WA
WA
QLD
WA
WA
SA
NSW
NSW
WA
WA
WA
WA
WA
SA
QLD
WA
WA
NSW
SA
SA
TA
SA
SA
SA
WA
WA
WA
SA
NSW
NSW
SA
SA
SA
WA
WA
WA
WA
SA
TA
NSW
NSW
SA
NSW
SA
SA
NSW
WA
SA
WA
SA
SA
QLD
QLD
QLD
NSW
QLD
SA
SA
SA
SA
VIC
SA
TA
QLD
WA
WA
SA
SA
SA
WA
SA
SA
WA
WA
NSW
SA
SA
SA
SA
SA
TA
SA
QLD
QLD
SA
SA
SA
NSW
WA
SA
SA
NSW
WA
WA
QLD
NSW
WA
VIC
VIC
QLD
WA
WA
WA
WA
NSW
NSW
SA
QLD
QLD
QLD
SA
SA
NSW
SA
QLD
QLD
WA
SA
SA
NSW
SA
QLD
SA
SA
SA
QLD
QLD
SA
SA
SA
NSW
SA
SA
WA
WA
SA
NSW
SA
WA
QLD
SA
SA
SA
SA
NSW
NSW
NSW
WA
WA
WA
SA
WA
TA
SA
SA
WA
SA
NSW
SA
SA
WA
WA
SA
SA
SA
QLD
WA
WA
WA
NSW
NSW
NSW
SA
VIC
VIC
VIC
VIC
WA
WA
WA
SA
SA
SA
SA
WA
WA
VIC
VIC
SA
SA
SA
NSW
NSW
QLD
QLD
QLD
WA
WA
SA
SA
SA
SA
QLD
SA
SA
SA
SA
WA
WA
WA
WA
WA
SA
QLD
NSW
QLD
SA
QLD
WA
SA
NSW
VIC
VIC
QLD
SA
QLD
WA
SA
SA
WA
NSW
QLD
NSW
QLD
SA
VIC
SA
SA
QLD
QLD
SA
NSW
SA
SA
SA
SA
SA
SA
SA
WA
WA
WA
WA
WA
SA
SA
SA
SA
QLD
QLD
SA
WA
SA
SA
WA
SA
SA
SA
SA
QLD
NSW
NSW
SA
SA
SA
WA
WA
QLD
QLD
QLD
TA
NSW
SA
SA
NSW
WA
WA
WA
SA
SA
QLD
SA
SA
SA
VIC
VIC
QLD
QLD
VIC
SA
SA
SA
SA
SA
TA
WA
WA
WA
SA
QLD
QLD
WA
QLD
QLD
QLD
QLD
SA
SA
QLD
WA
WA
SA
SA
WA
WA
SA
SA
SA
SA
SA
VIC
SA
TA
QLD
QLD
QLD
QLD
WA
WA
SA
WA
WA
WA
SA
WA
QLD
WA
QLD
WA
QLD
WA
WA
QLD
WA
SA
SA
WA
WA
WA
WA
NSW
SA
WA
SA
NSW
NSW
QLD
SA
SA
SA
WA
WA
WA
WA
QLD
QLD
QLD
VIC
SA
QLD
QLD
WA
SA
WA
SA
SA
WA
WA
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
WA
VIC
SA
SA
SA
SA
WA
QLD
QLD
WA
WA
WA
WA
SA
SA
SA
SA
SA
WA
QLD
SA
NSW
NSW
NSW
WA
SA
SA
WA
WA
SA
NSW
QLD
QLD
SA
SA
SA
SA
SA
SA
SA
SA
VIC
WA
WA
SA
QLD
VIC
SA
SA
SA
SA
SA
VIC
WA
SA
QLD
SA
SA
SA
WA
WA
WA
WA
WA
SA
SA
SA
SA
SA
WA
WA
WA
WA
WA
NSW
SA
SA
SA
WA
SA
SA
SA
NSW
NSW
VIC
VIC
QLD
QLD
QLD
SA
SA
WA
WA
VIC
NSW
NSW
NSW
WA
SA
SA
SA
WA
WA
SA
SA
NSW
SA
WA
WA
WA
SA
SA
SA
SA
SA
QLD
QLD
QLD
QLD
WA
WA
SA
SA
NSW
QLD
SA
SA
SA
SA
NSW
NSW
NSW
SA
SA
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
QLD
QLD
QLD
WA
WA
WA
SA
SA
WA
SA
SA
SA
WA
SA
SA
SA
SA
SA
SA
SA
WA
SA
VIC
WA
WA
SA
SA
SA
SA
NSW
WA
SA
WA
WA
WA
QLD
SA
WA
WA
WA
WA
SA
SA
SA
SA
SA
WA
SA
SA
SA
SA
WA
QLD
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
NSW
WA
WA
VIC
WA
WA
WA
WA
SA
NSW
NSW
NSW
SA
SA
WA
WA
SA
NSW
WA
SA
WA
SA
WA
QLD
QLD
WA
WA
QLD
WA
WA
WA
WA
WA
WA
WA
WA
WA
SA
SA
SA
NSW
NSW
WA
WA
SA
SA
WA
WA
WA
SA
SA
SA
NSW
QLD
NSW
WA
WA
WA
QLD
TA
TA
WA
SA
SA
NSW
VIC
VIC
VIC
TA
TA
SA
WA
QLD
SA
SA
QLD
SA
NSW
SA
SA
SA
SA
SA
SA
QLD
NSW
WA
WA
WA
SA
WA
SA
VIC
VIC
QLD
SA
QLD
WA
WA
QLD
QLD
VIC
WA
SA
SA
SA
SA
QLD
WA
WA
WA
SA
VIC
SA
SA
VIC
QLD
QLD
QLD
QLD
QLD
SA
VIC
VIC
QLD
QLD
WA
SA
NSW
QLD
SA
SA
NSW
WA
SA
WA
VIC
NSW
VIC
VIC
VIC
VIC
SA
QLD
WA
WA
WA
NSW
SA
WA
WA
VIC
QLD
QLD
WA
WA
QLD
SA
SA
VIC
WA
WA
WA
WA
QLD
QLD
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
QLD
QLD
QLD
QLD
VIC
SA
SA
SA
WA
QLD
NSW
NSW
SA
SA
SA
NSW
VIC
TA
SA
QLD
NSW
QLD
QLD
QLD
SA
WA
WA
QLD
SA
SA
SA
NSW
WA
WA
WA
SA
SA
SA
WA
WA
SA
WA
WA
SA
WA
WA
WA
WA
WA
SA
SA
SA
QLD
TA
VIC
SA
SA
NSW
SA
SA
SA
SA
NSW
SA
SA
WA
WA
SA
SA
SA
SA
SA
SA
WA
VIC
SA
SA
SA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
WA
WA
TA
TA
QLD
TA
TA
TA
SA
WA
QLD
VIC
VIC
SA
SA
SA
SA
WA
WA
WA
WA
WA
WA
WA
QLD
QLD
QLD
QLD
QLD
QLD
SA
WA
WA
WA
WA
SA
SA
QLD
SA
WA
VIC
SA
SA
SA
SA
SA
QLD
SA
QLD
QLD
SA
SA
WA
SA
SA
SA
SA
TA
TA
VIC
VIC
VIC
VIC
VIC
SA
WA
WA
SA
WA
WA
QLD
QLD
SA
WA
NSW
QLD
WA
WA
WA
WA
WA
SA
VIC
VIC
WA
QLD
WA
WA
WA
WA
WA
NSW
NSW
NSW
WA
SA
SA
NSW
NSW
QLD
SA
SA
WA
SA
SA
SA
SA
SA
NSW
NSW
QLD
NSW
SA
SA
NSW
QLD
QLD
SA
WA
WA
VIC
QLD
QLD
QLD
VIC
SA
SA
SA
QLD
QLD
NSW
SA
WA
QLD
QLD
WA
WA
SA
SA
SA
SA
SA
SA
SA
VIC
VIC
WA
WA
WA
QLD
SA
QLD
SA
SA
SA
SA
SA
WA
SA
SA
WA
WA
SA
SA
SA
SA
NSW
WA
TA
QLD
QLD
QLD
VIC
WA
VIC
SA
WA
VIC
SA
WA
NSW
SA
QLD
SA
SA
WA
WA
SA
SA
WA
WA
WA
WA
WA
WA
WA
SA
WA
WA
WA
WA
VIC
QLD
QLD
VIC
SA
SA
SA
SA
SA
SA
NSW
WA
WA
TA
WA
WA
WA
SA
SA
SA
SA
NSW
WA
WA
WA
WA
SA
WA
WA
WA
WA
WA
WA
WA
NSW
NSW
NSW
VIC
WA
VIC
SA
SA
SA
SA
WA
SA
SA
SA
SA
SA
QLD
QLD
SA
SA
QLD
NSW
NSW
QLD
WA
SA
SA
VIC
WA
VIC
WA
QLD
QLD
QLD
SA
SA
SA
VIC
SA
NSW
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
WA
WA
WA
WA
WA
QLD
QLD
SA
NSW
WA
WA
WA
SA
NSW
NSW
WA
WA
SA
SA
NSW
WA
WA
WA
WA
WA
WA
WA
WA
SA
WA
WA
SA
SA
VIC
SA
SA
VIC
SA
SA
WA
WA
WA
SA
WA
WA
SA
SA
SA
NSW
SA
SA
SA
WA
SA
SA
SA
SA
NSW
VIC
WA
WA
WA
NSW
SA
SA
SA
SA
QLD
QLD
QLD
QLD
QLD
SA
VIC
VIC
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
NSW
WA
WA
SA
WA
VIC
SA
SA
NSW
SA
SA
QLD
SA
QLD
WA
QLD
SA
QLD
WA
WA
WA
SA
SA
NSW
NSW
SA
WA
WA
SA
SA
SA
SA
QLD
SA
QLD
QLD
WA
SA
SA
SA
VIC
SA
VIC
QLD
SA
QLD
SA
SA
SA
WA
WA
WA
SA
SA
WA
SA
SA
SA
SA
WA
WA
WA
SA
WA
WA
QLD
TA
VIC
WA
SA
WA
WA
WA
QLD
SA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
WA
SA
WA
QLD
QLD
SA
SA
WA
WA
WA
WA
SA
SA
SA
SA
QLD
WA
SA
SA
SA
VIC
WA
WA
WA
WA
QLD
SA
WA
SA
SA
QLD
NSW
SA
SA
SA
SA
VIC
SA
QLD
SA
WA
QLD
QLD
QLD
SA
SA
WA
SA
SA
SA
NSW
SA
QLD
SA
SA
SA
QLD
QLD
QLD
QLD
QLD
SA
SA
SA
SA
SA
SA
SA
WA
VIC
WA
NSW
NSW
NSW
NSW
VIC
VIC
VIC
VIC
VIC
VIC
WA
SA
SA
SA
SA
SA
SA
VIC
WA
WA
VIC
WA
WA
WA
SA
WA
NSW
WA
SA
WA
QLD
QLD
QLD
NSW
WA
SA
NSW
NSW
VIC
QLD
NSW
QLD
QLD
VIC
SA
SA
WA
VIC
VIC
WA
WA
WA
QLD
NSW
WA
QLD
SA
WA
SA
SA
WA
VIC
WA
VIC
SA
SA
QLD
SA
SA
VIC
SA
SA
SA
NSW
SA
QLD
SA
SA
QLD
QLD
WA
WA
WA
SA
SA
VIC
VIC
VIC
SA
NSW
SA
SA
SA
SA
VIC
WA
WA
WA
WA
SA
SA
SA
TA
QLD
WA
QLD
SA
NSW
NSW
QLD
QLD
SA
SA
VIC
SA
SA
SA
VIC
QLD
QLD
QLD
QLD
QLD
QLD
WA
SA
NSW
WA
SA
SA
SA
SA
WA
SA
SA
VIC
VIC
WA
VIC
SA
SA
SA
WA
NSW
NSW
SA
WA
WA
NSW
NSW
SA
WA
NSW
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
NSW
WA
QLD
NSW
QLD
QLD
VIC
VIC
VIC
VIC
VIC
WA
TA
TA
WA
WA
SA
SA
TA
QLD
SA
SA
SA
SA
SA
NSW
WA
VIC
QLD
WA
QLD
WA
NSW
QLD
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
QLD
WA
WA
WA
SA
SA
QLD
QLD
QLD
WA
QLD
QLD
SA
SA
SA
QLD
QLD
SA
SA
QLD
SA
SA
SA
SA
SA
VIC
SA
SA
VIC
VIC
SA
SA
WA
WA
NSW
WA
WA
SA
WA
SA
SA
SA
QLD
QLD
TA
VIC
SA
QLD
WA
WA
QLD
QLD
WA
WA
WA
SA
QLD
TA
NSW
QLD
QLD
QLD
QLD
QLD
QLD
QLD
WA
VIC
SA
SA
SA
SA
VIC
NSW
SA
QLD
SA
WA
VIC
VIC
SA
SA
WA
WA
TA
TA
WA
WA
SA
SA
QLD
QLD
QLD
SA
SA
SA
TA
TA
TA
TA
SA
SA
SA
QLD
SA
WA
SA
SA
SA
NSW
NSW
WA
WA
WA
SA
QLD
WA
SA
WA
VIC
SA
TA
SA
QLD
QLD
QLD
QLD
VIC
QLD
NSW
QLD
SA
SA
SA
SA
SA
SA
WA
QLD
QLD
VIC
QLD
QLD
SA
SA
SA
SA
SA
SA
VIC
QLD
WA
WA
SA
SA
SA
SA
SA
SA
WA
WA
VIC
SA
SA
SA
VIC
SA
SA
SA
VIC
VIC
VIC
WA
TA
TA
TA
TA
WA
WA
SA
NSW
NSW
NSW
SA
SA
SA
SA
SA
SA
VIC
VIC
TA
TA
WA
WA
WA
WA
SA
WA
WA
WA
WA
SA
SA
SA
SA
QLD
QLD
QLD
QLD
QLD
QLD
WA
VIC
VIC
WA
VIC
WA
SA
SA
SA
WA
VIC
QLD
WA
NSW
NSW
VIC
VIC
TA
TA
QLD
QLD
WA
SA
SA
SA
SA
QLD
QLD
QLD
QLD
VIC
VIC
SA
SA
WA
WA
SA
QLD
QLD
QLD
SA
QLD
WA
SA
SA
SA
QLD
WA
WA
SA
NSW
NSW
WA
NSW
QLD
QLD
QLD
SA
WA
SA
SA
NSW
SA
SA
NSW
VIC
SA
QLD
SA
SA
SA
SA
QLD
SA
WA
WA
VIC
NSW
WA
WA
SA
VIC
VIC
VIC
VIC
SA
SA
NSW
NSW
WA
WA
WA
WA
QLD
SA
SA
SA
QLD
SA
SA
NSW
NSW
WA
QLD
SA
SA
SA
NSW
VIC
SA
SA
QLD
WA
VIC
TA
TA
TA
WA
SA
SA
VIC
VIC
SA
SA
SA
WA
SA
QLD
QLD
QLD
TA
QLD
QLD
QLD
WA
SA
SA
QLD
SA
SA
QLD
QLD
QLD
QLD
VIC
QLD
QLD
NSW
WA
NSW
VIC
TA
TA
SA
WA
WA
WA
SA
SA
WA
WA
SA
SA
SA
QLD
QLD
WA
WA
VIC
VIC
QLD
WA
WA
WA
WA
QLD
SA
SA
SA
SA
SA
SA
SA
WA
WA
WA
SA
WA
WA
SA
NSW
WA
WA
SA
SA
TA
TA
TA
WA
SA
NSW
NSW
QLD
QLD
QLD
SA
SA
QLD
VIC
WA
VIC
WA
VIC
SA
VIC
NSW
NSW
SA
QLD
SA
TA
TA
NSW
WA
SA
NSW
WA
WA
NSW
WA
NSW
NSW
VIC
VIC
SA
VIC
WA
SA
QLD
QLD
WA
WA
WA
SA
NSW
WA
QLD
SA
VIC
QLD
QLD
QLD
VIC
WA
VIC
SA
WA
QLD
QLD
VIC
WA
WA
WA
WA
WA
WA
WA
NSW
WA
QLD
SA
SA
SA
SA
WA
WA
SA
SA
TA
WA
WA
WA
SA
SA
WA
QLD
QLD
QLD
SA
SA
SA
SA
SA
SA
SA
QLD
QLD
SA
SA
SA
SA
NSW
SA
VIC
SA
NSW
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
VIC
QLD
SA
WA
QLD
SA
VIC
TA
SA
QLD
SA
QLD
SA
SA
VIC
VIC
WA
VIC
WA
VIC
WA
WA
WA
SA
SA
SA
QLD
SA
SA
SA
SA
SA
SA
SA
SA
WA
WA
WA
TA
TA
QLD
QLD
QLD
QLD
WA
SA
SA
SA
SA
SA
SA
SA
SA
WA
NSW
QLD
SA
WA
QLD
QLD
WA
WA
QLD
SA
SA
QLD
WA
WA
WA
WA
WA
SA
WA
VIC
NSW
SA
SA
WA
WA
SA
QLD
QLD
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
NSW
SA
SA
VIC
QLD
SA
SA
WA
WA
NSW
VIC
TA
VIC
VIC
VIC
QLD
WA
WA
QLD
NSW
SA
WA
SA
QLD
VIC
NSW
SA
SA
SA
TA
WA
WA
WA
WA
QLD
WA
WA
WA
WA
WA
TA
WA
WA
SA
WA
WA
WA
SA
SA
SA
WA
QLD
NSW
SA
WA
WA
TA
WA
SA
SA
SA
NSW
QLD
QLD
WA
NSW
NSW
QLD
SA
NSW
NSW
NSW
NSW
NSW
NSW
NSW
NSW
NSW
WA
NSW
VIC
SA
QLD
VIC
SA
WA
VIC
WA
WA
VIC
VIC
VIC
WA
WA
WA
WA
WA
WA
WA
SA
NSW
VIC
TA
WA
VIC
QLD
SA
SA
SA
WA
WA
WA
SA
WA
WA
VIC
SA
SA
SA
NSW
WA
WA
WA
WA
WA
WA
WA
SA
SA
WA
SA
WA
WA
WA
WA
SA
SA
WA
WA
WA
WA
WA
VIC
WA
SA
WA
WA
SA
QLD
SA
SA
SA
SA
QLD
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
VIC
WA
WA
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
SA
SA
WA
WA
VIC
VIC
WA
WA
WA
WA
WA
SA
SA
SA
SA
VIC
QLD
NSW
SA
WA
WA
WA
WA
WA
VIC
VIC
VIC
QLD
SA
WA
WA
WA
WA
WA
SA
VIC
NSW
WA
SA
WA
QLD
WA
VIC
WA
SA
NSW
SA
QLD
QLD
SA
QLD
QLD
QLD
QLD
QLD
QLD
NSW
SA
SA
SA
SA
NSW
NSW
NSW
SA
WA
WA
QLD
WA
QLD
QLD
SA
SA
TA
TA
TA
QLD
WA
WA
QLD
SA
WA
TA
SA
QLD
QLD
SA
SA
QLD
WA
SA
QLD
WA
SA
SA
SA
NSW
SA
QLD
QLD
SA
SA
SA
QLD
QLD
SA
SA
WA
SA
SA
WA
SA
SA
QLD
QLD
QLD
SA
WA
QLD
WA
SA
SA
QLD
SA
VIC
VIC
SA
WA
SA
TA
TA
SA
SA
WA
SA
SA
SA
SA
SA
VIC
SA
QLD
VIC
SA
SA
SA
SA
SA
SA
SA
SA
VIC
SA
SA
SA
SA
SA
WA
WA
NSW
VIC
SA
WA
SA
SA
QLD
QLD
QLD
SA
SA
SA
WA
WA
WA
WA
SA
SA
SA
NSW
NSW
WA
WA
NSW
SA
QLD
WA
WA
SA
SA
WA
WA
WA
WA
VIC
SA
QLD
QLD
WA
SA
QLD
SA
QLD
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
VIC
WA
WA
WA
WA
SA
SA
NSW
NSW
NSW
NSW
NSW
NSW
NSW
WA
WA
WA
SA
WA
WA
WA
WA
TA
WA
WA
WA
QLD
WA
WA
WA
WA
WA
WA
WA
WA
WA
QLD
WA
WA
SA
SA
SA
SA
SA
WA
NSW
VIC
WA
WA
SA
SA
SA
QLD
SA
WA
QLD
WA
SA
NSW
NSW
WA
SA
TA
VIC
WA
SA
SA
SA
SA
SA
SA
WA
QLD
SA
WA
SA
VIC
WA
VIC
SA
WA
WA
WA
WA
SA
SA
WA
QLD
WA
WA
QLD
VIC
NSW
QLD
QLD
SA
SA
QLD
QLD
SA
QLD
QLD
WA
WA
SA
SA
SA
SA
NSW
WA
WA
WA
WA
SA
SA
NSW
SA
SA
QLD
WA
WA
WA
WA
WA
WA
WA
WA
WA
SA
SA
WA
WA
WA
WA
QLD
VIC
VIC
WA
SA
WA
SA
SA
VIC
VIC
VIC
NSW
NSW
WA
WA
WA
TA
QLD
WA
SA
SA
SA
NSW
SA
VIC
WA
WA
WA
WA
VIC
VIC
NSW
QLD
QLD
SA
WA
WA
SA
SA
QLD
QLD
QLD
VIC
VIC
WA
QLD
NSW
NSW
WA
WA
QLD
VIC
NSW
QLD
QLD
SA
VIC
WA
WA
NSW
WA
WA
WA
NSW
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
WA
SA
SA
SA
VIC
VIC
VIC
SA
WA
SA
SA
SA
SA
SA
WA
QLD
WA
WA
VIC
SA
WA
WA
WA
SA
SA
QLD
WA
WA
NSW
NSW
NSW
SA
SA
QLD
SA
WA
QLD
WA
WA
SA
QLD
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
VIC
SA
QLD
SA
QLD
SA
SA
SA
SA
SA
SA
SA
WA
WA
WA
WA
WA
NSW
WA
NSW
VIC
QLD
SA
VIC
NSW
SA
SA
SA
SA
SA
SA
SA
SA
SA
NSW
SA
WA
WA
WA
SA
QLD
WA
WA
SA
NSW
SA
SA
VIC
SA
SA
WA
SA
SA
SA
VIC
SA
QLD
SA
WA
WA
WA
WA
NSW
SA
WA
SA
SA
VIC
QLD
NSW
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
SA
WA
WA
NSW
SA
QLD
QLD
QLD
VIC
VIC
WA
WA
SA
NSW
SA
SA
SA
SA
WA
WA
SA
SA
VIC
VIC
WA
WA
VIC
WA
NSW
SA
SA
QLD
WA
WA
WA
WA
WA
WA
SA
WA
WA
NSW
VIC
VIC
SA
SA
SA
SA
SA
WA
WA
WA
WA
QLD
WA
WA
SA
SA
SA
SA
QLD
WA
WA
SA
NSW
QLD
NSW
WA
WA
WA
WA
WA
WA
SA
SA
SA
QLD
VIC
QLD
VIC
SA
SA
QLD
WA
NSW
SA
SA
NSW
NSW
NSW
TA
QLD
WA
SA
SA
SA
SA
WA
WA
SA
SA
SA
WA
QLD
QLD
QLD
QLD
QLD
QLD
QLD
SA
SA
SA
QLD
QLD
SA
QLD
QLD
WA
NSW
NSW
NSW
WA
VIC
WA
VIC
SA
SA
SA
SA
WA
WA
WA
SA
SA
SA
WA
QLD
QLD
SA
SA
WA
SA
SA
SA
SA
WA
SA
WA
WA
SA
WA
SA
WA
WA
WA
WA
QLD
QLD
WA
SA
WA
WA
VIC
NSW
NSW
WA
WA
WA
NSW
SA
WA
WA
WA
SA
NSW
SA
SA
WA
WA
QLD
SA
SA
SA
VIC
QLD
QLD
QLD
QLD
QLD
SA
SA
SA
TA
TA
WA
WA
QLD
QLD
WA
WA
WA
SA
SA
SA
QLD
WA
WA
WA
SA
SA
SA
SA
QLD
QLD
NSW
WA
VIC
SA
SA
WA
SA
WA
SA
SA
SA
VIC
VIC
QLD
QLD
SA
VIC
QLD
QLD
QLD
WA
WA
WA
WA
WA
WA
SA
VIC
WA
SA
WA
WA
SA
WA
SA
NSW
WA

In [5]:
#Vehicle Marketing Type是FH13 64T但是与前一行不同
list_new_column = ['previous row not exist']

for n in range(1,rc):
    if df['Vehicle Marketing Type'][n] == 'FH13 64T' and df['Vehicle Marketing Type'][n] != df['Vehicle Marketing Type'][n-1]:
        list_new_column.append('not same model with previous row')
    else:
        list_new_column.append('same model with previous row')

df['if_model_same_with_prev_row'] = list_new_column
df['if_model_same_with_prev_row']

0              previous row not exist
1        same model with previous row
2        same model with previous row
3        same model with previous row
4        same model with previous row
                     ...
24374    same model with previous row
24375    same model with previous row
24376    same model with previous row
24377    same model with previous row
24378    same model with previous row
Name: if_model_same_with_prev_row, Length: 24379, dtype: object

In [6]:
#Causal Part Name 每行最后5个数
list_new_column = []
    
for n in range(1,rc):
    print(df['Causal Part Name'][n][:5])

SEALI
EXHAU
INJEC
OIL P
OIL L
PRESS
FAN,
PRESS
OIL H
EXHAU
EXHAU
PRESS
BELT
UNIT,
BELT
DIAPH
BELT
EXHAU
TURBO
EXHAU
PRESS
SENSO
SEALI
OIL F
SENSO
CONTR
BRACK
CAMSH
OIL P
SENSO
SENSO
CRANK
CAMSH
AIR H
SOLEN
CAMSH
INJEC
EXHAU
INJEC
EXHAU
SENSO
EXHAU
EXHAU
PRESS
PRESS
PRESS
PRESS
PRESS
EXHAU
PRESS
LIP S
COMPA
EXHAU
AIR V
PIPE
TEMPE
ACTUA
SOLEN
SOLEN
GASKE
SEALI
TIMIN
OIL F
BELT
CRANK
CHARG
EXHAU
SEALI
OIL H
OIL H
CYLIN
SENSO
OIL H
GASKE
OIL F
BELT
CHARG
DIAPH
GASKE
PRESS
PRESS
TEMPE
PRESS
SPEED
PRESS
PRESS
OIL H
PRESS
EXHAU
SENSO
RADIA
RADIA
RADIA
PRESS
OIL F
PRESS
PRESS
PRESS
PRESS
CONTR
OIL F
DIAPH
PRESS
PISTO
EXHAU
EXHAU
PRESS
FLYWH
GASKE
PRESS
PRESS
VALVE
EXHAU
TURBO
ROCKE
GASKE
OIL F
BELT
IDLER
PRESS
CONTR
CONTR
PRESS
CONTR
BELT
IDLER
INLET
ACTUA
IDLER
PRESS
BELT
EXHAU
EXHAU
PRESS
EXHAU
OIL H
ACTUA
ACTUA
OIL H
OIL H
OIL H
OIL H
CRANK
GASKE
OIL H
OIL H
SEALI
TEMPE
BELT
EXHAU
EXHAU
CHARG
PRESS
PRESS
PRESS
SEALI
EXHAU
EXHAU
TURBO
RADIA
EXHAU
EXHAU
UNIT
EXHAU
AIR V
PIPE
PRESS
PRESS
TEMPE
EXHAU
ACTUA
GASKE
EXHAU
RADIA
STUD,
EXHAU
EXHAU
CAMSH
EXHAU
IDLER
EXHAU
EXHAU
TURBO
EXHAU
EXHAU
EXHAU
AIR V
POSIT
EXHAU
TURBO
PRESS
EXHAU
TURBO
EXHAU
OIL H
EXHAU
IDLER
EXHAU
BELT
SEALI
TURBO
OIL H
CONNE
TURBO
TURBO
EXHAU
CYLIN
ROCKE
TIMIN
AIR V
TURBO
TURBO
REPAI
OIL H
EXHAU
EXHAU
TURBO
CHARG
TEMPE
GASKE
PRESS
EXHAU
EXHAU
BELT
TURBO
PUMP
COVER
EXHAU
CONTR
PUMP
PRESS
PRESS
PRESS
CONNE
CONTR
INLET
FLANG
EXHAU
DIAPH
FAN,
BELT
EXHAU
PRESS
CONTR
SENSO
COVER
EXHAU
TURBO
GEAR
GEAR
GASKE
EXHAU
TURBO
SEALI
OIL F
TURBO
SENSO
SEALI
PRESS
IDLER
CONTR
AIR V
ROLLE
TIMIN
FLYWH
SEALI
TEMPE
AIR V
CHARG
PRESS
TEMPE
BELT
BELT
PRESS
EXHAU
SEALI
RADIA
TIMIN
IDLER
TEMPE
GROMM
GASKE
OIL L
SPEED
TIMIN
DIAPH
FLYWH
TIMIN
FLYWH
RADIA
INJEC
FLYWH
IDLER
GASKE
SEALI
LIP S
CONTR
TIMIN
TIMIN
CRANK
PIPE,
EXHAU
OIL H
OIL H
EXHAU
SENSO
TEMPE
INJEC
BELT
SEALI
FLYWH
CRANK
PRESS
BELT
IDLER
OIL H
OIL H
RADIA
PRESS
GASKE
VALVE
EXHAU
PRESS
SOLEN
OIL H
OIL F
PRESS
SOLEN
SEALI
FLYWH
PRESS
CYLIN
SOLEN
FLYWH
DIAPH
FAN H
EXHAU
DIAPH
CONTR
GEAR
BELT
CYLIN
SOLEN
SOLEN
FLYWH
FLYWH
SEALI
PRESS
BELT
BELT
TEMPE
DIAPH
OIL H
OIL H
SUPPO
BELT
TIMIN
IDLER
HOSE,
TURBO
FAN,
BELT
PRESS
OIL P
CONTR
SLEEV
PRESS
PRESS
OIL L
OIL L
PRESS
OIL P
PRESS
SENSO
OIL F
PRESS
INJEC
INLET
PRESS
SOLEN
SEALI
SENSO
CONTR
OIL F
EXHAU
BRACK
SEALI
EXHAU
OIL L
SEALI
PRESS
EXHAU
CONTR
EXHAU
BELT
OIL H
EXHAU
CONTR
PRESS
BELT
TURBO
PUMP
FILLE
COOLA
CONTR
EXHAU
PUMP
BELT
SENSO
INSPE
BELT
EXHAU
PUMP
OIL H
SENSO
OIL H
BELT
SENSO
OIL P
EXHAU
TURBO
EXHAU
AIR V
OIL H
OIL H
CRANK
SEALI
BELT
BELT
BELT
OIL P
THERM
OIL H
OIL H
SENSO
GASKE
CRANK
CONTR
PRESS
PRESS
PRESS
CONTR
PRESS
OIL L
PRESS
PRESS
PRESS
PRESS
FAN,
PRESS
SENSO
GEAR,
PRESS
PRESS
OIL H
PRESS
BELT
PRESS
COOLA
CYLIN
FAN,
FAN,
SENSO
INJEC
OIL F
PRESS
EXHAU
OIL L
PRESS
IDLER
SENSO
FAN,
SENSO
EXPAN
PRESS
BELT
BELT
EXHAU
EXHAU
EXHAU
EXHAU
PRESS
PRESS
PRESS
FAN,
PRESS
OIL F
EXHAU
EXHAU
PRESS
OIL F
EXHAU
ACTUA
OIL F
OIL H
OIL H
OIL H
EXHAU
SEALI
EXPAN
OIL H
OIL H
ACTUA
OIL H
OIL H
SEAL,
COMPA
PRESS
THERM
BELT
SEALI
CONTR
BELT
BELT
IDLER
OIL L
PRESS
OIL H
OIL H
CONTR
PRESS
SENSO
EXHAU
PRESS
TIMIN
CAMSH
EXHAU
CAMSH
BELT
CYLIN
EXHAU
FAN,
ACTUA
BELT
SOLEN
EXHAU
GASKE
OIL H
OIL L
GASKE
OIL H
FUEL
PRESS
CRANK
DIPST
EXHAU
AIR V
TURBO
FAN,
OIL L
CYLIN
INPUT
EXHAU
EXHAU
CYLIN
COOLA
SOLEN
RADIA
PRESS
EXHAU
FAN,
TURBO
FAN,
EXHAU
CLAMP
TURBO
PRESS
EXHAU
PRESS
TIMIN
PRESS
FAN,
PRESS
PRESS
OIL H
PRESS
SEALI
OIL F
DIAPH
BEARI
PRESS
SEALI
OIL L
SEAL,
EXHAU
BELT
PRESS
TEMPE
SEALI
PRESS
RADIA
OIL H
PRESS
PRESS
TEMPE
CYLIN
SOLEN
UNIT
FAN H
FAN,
EXHAU
PRESS
CRANK
PRESS
PRESS
EXHAU
EXHAU
AIR V
TURBO
SENSO
FAN,
OIL H
BELT
PRESS
CYLIN
OIL F
EXHAU
OIL L
CRANK
OIL H
OIL H
BELT
PRESS
OIL P
ENGIN
PRESS
PRESS
TEMPE
CLUTC
SEALI
PRESS
PRESS
PRESS
EXHAU
EXHAU
EXHAU
PRESS
PRESS
BALL
CYLIN
SEALI
EXHAU
OIL H
OIL H
TIMIN
EXHAU
AIR V
SPEED
OIL H
FILTE
BELT
BELT
IDLER
CONNE
GASKE
OIL L
SEALA
EXHAU
CHARG
BELT
TURBO
BELT
SEALI
EXHAU
ACTUA
ROCKE
CYLIN
BELT
PRESS
OIL F
SENSO
UNIT,
CONNE
EXHAU
SEALI
PRESS
COVER
OIL P
EXHAU
EXHAU
CHARG
OIL F
BELT
BELT
IDLER
IDLER
INJEC
CYLIN
PASS-
FLYWH
IDLER
TURBO
EXHAU
GASKE
PRESS
OIL H
BELT
BELT
FILLE
CHARG
CHARG
EXHAU
EXHAU
EXHAU
CHARG
SEALA
BELT
OIL H
PRESS
TEMPE
PRESS
EXHAU
EXHAU
BELT
CONTR
COOLA
PIPE,
FAN,
EXHAU
BELT
BELT
EXHAU
OIL F
OIL L
PRESS
PRESS
OIL F
TIMIN
EXHAU
COOLA
PRESS
ACTUA
ACTUA
SENSO
PRESS
BELT
LIP S
CAMSH
THRUS
OIL P
OIL F
EXHAU
INJEC
SENSO
OIL H
DIAPH
RADIA
OIL F
PRESS
SENSO
SENSO
SOLEN
EXHAU
CONTR
OIL L
PRESS
EXHAU
BELT
IDLER
OIL H
ACTUA
IDLER
EXHAU
TEMPE
RADIA
CAMSH
EXPAN
FILLE
PRESS
BELT
BELT
IDLER
GEAR
TEMPE
FAN H
FAN,
BELT
BELT
IDLER
SUPPO
LIP S
BELT
CONNE
OIL F
BELT
IDLER
EXHAU
FLYWH
GASKE
SENSO
TIMIN
PRESS
PASS-
FLYWH
AIR H
INJEC
FLYWH
CHARG
EXHAU
PRESS
EXHAU
PRESS
IDLER
FLYWH
COVER
SEALA
EXHAU
CONTR
INLET
GASKE
EXHAU
GASKE
BELT
BELT
SENSO
OIL F
OIL H
SOLEN
OIL H
PRESS
EXHAU
AIR V
BELT
SENSO
INJEC
OVERF
UNIT
CLUTC
GASKE
OIL H
OIL H
FAN,
EXHAU
ACTUA
AIR V
OIL H
PRESS
FAN,
OIL H
SEALI
EXHAU
ACTUA
OIL F
OIL L
DIPST
BELT
TIMIN
SENSO
BALL
OIL P
OIL C
FAN,
EXHAU
SEALI
SENSO
PRESS
PRESS
PRESS
OIL H
SEALI
GASKE
EXHAU
CRANK
SEALI
PRESS
SOFTW
TURBO
PRESS
EXHAU
EXHAU
INJEC
SEALI
BELT
FLYWH
TIMIN
PRESS
OIL H
SEALA
PRESS
PUMP
FAN H
OIL H
CONTR
EXHAU
EXHAU
SENSO
PASS-
SEALI
BELT
SUPPO
CYLIN
PRESS
COVER
EXHAU
EXHAU
PUMP
SEAL
SEALI
FLYWH
OIL H
BELT
BELT
IDLER
TIMIN
PIPE,
PIPE,
FLYWH
BELT
FLYWH
TIMIN
SEALI
EXHAU
CHARG
BELT
SENSO
PRESS
IDLER
COOLI
PRESS
TEMPE
PASS-
PRESS
PRESS
CYLIN
CYLIN
INPUT
PRESS
BELT
SEALI
OIL L
SENSO
CONTR
CONTR
OIL P
EXHAU
BELT
EXHAU
PRESS
IDLER
EXHAU
OIL L
PASS-
SENSO
OIL H
FAN,
SENSO
FAN,
OIL H
OIL H
SENSO
EXHAU
EXHAU
OIL H
OIL P
LIP S
SENSO
SENSO
SEALI
SEALI
BELT
BELT
CHARG
WIRIN
EXHAU
EXHAU
SENSO
TIMIN
EXHAU
FAN,
EXHAU
TURBO
BELT
SUPPO
EXHAU
PRESS
OIL P
EXHAU
PUMP
EXHAU
CHARG
ROCKE
PRESS
TIMIN
OIL P
EXHAU
TIMIN
IDLER
PRESS
BELT
FLYWH
PUMP
FLYWH
FLYWH
EXHAU
FLYWH
CONNE
CHARG
BELT
COVER
PRESS
PRESS
SEALI
RADIA
PRESS
INJEC
PRESS
PRESS
BELT
EXHAU
EXHAU
EXHAU
EXHAU
CONTR
EXHAU
BELT
GASKE
EXHAU
EXHAU
EXHAU
PRESS
CLUTC
BELT
OIL H
EXHAU
EXHAU
OIL H
EXHAU
CAMSH
EXHAU
SEALI
PRESS
FUEL
GEAR
EXHAU
BELT
PRESS
DOSAG
SEALA
KIT,
SEALI
RADIA
GASKE
SOFTW
OIL L
BELT
CHARG
PRESS
CYLIN
OIL F
SEALI
OIL H
OIL H
FAN,
OIL L
PRESS
OIL H
OIL H
PRESS
PRESS
SENSO
EXHAU
SENSO
OIL H
EXHAU
EXHAU
PRESS
EXHAU
EXHAU
OIL H
OIL H
EXHAU
EXHAU
OIL H
PRESS
OIL F
EXHAU
EXHAU
BELT
RADIA
BELT
TEMPE
GEAR
PRESS
COMPA
EXHAU
BELT
IDLER
DIFFE
BELT
PRESS
CONNE
SOLEN
ACTUA
TEMPE
ROLLE
TIMIN
FLYWH
OIL P
PRESS
PUMP
OIL H
PRESS
EXHAU
PRESS
BELT
SENSO
FAN,
CYLIN
RUBBE
EXHAU
TURBO
EXHAU
DIAPH
PRESS
TEMPE
EXHAU
PRESS
OIL H
OIL H
EXHAU
TIMIN
CAMSH
EXHAU
EXHAU
EXHAU
PRESS
IDLER
EXHAU
FAN,
BELT
SEALI
PASS-
PIPE,
TEMPE
EXHAU
PRESS
CONTR
INJEC
EXHAU
EXHAU
BELT
TIMIN
TEMPE
FAN,
IDLER
TIMIN
IDLER
INJEC
PRESS
IDLER
OIL F
LIP S
FLANG
OIL L
ROCKE
IDLER
SEALI
BELT
BELT
IDLER
SEALI
PRESS
OIL F
IDLER
OIL H
OIL H
EXHAU
CAMSH
SEALI
SEALI
SENSO
SEALI
OIL H
PRESS
PRESS
PRESS
OIL F
SEALI
FAN,
EXHAU
SEALI
BELT
CAMSH
EXHAU
COOLA
TURBO
FAN,
BELT
BELT
MUFFL
TURBO
BELT
EXHAU
START
START
SEALI
TIMIN
OIL F
SEALI
BELT
FLYWH
GASKE
TIMIN
FLYWH
OIL H
EXHAU
TURBO
PRESS
FLYWH
IDLER
IDLER
ACTUA
OIL L
OIL L
FLYWH
FILTE
FLANG
IDLER
EXHAU
PASS-
MUFFL
FLYWH
PRESS
DOSAG
TEMPE
MUFFL
PUMP
CRANK
OIL L
SENSO
CRANK
OIL L
PRESS
EXHAU
OIL L
EXHAU
INLET
TURBO
FAN,
SEALI
EXHAU
EXHAU
CONTR
CONTR
PRESS
PRESS
CYLIN
FAN,
PRESS
MAIN
CONTR
EXHAU
PRESS
CONTR
BELT
OIL P
SENSO
CONTR
PRESS
INJEC
EXHAU
OIL H
INJEC
SPEED
FLANG
EXHAU
OIL L
SEALA
WIRIN
OIL F
TIMIN
EXPAN
CRANK
CYLIN
EXHAU
FAN,
EXHAU
FAN,
BELT
CAMSH
DIAPH
SEALI
EXHAU
PRESS
MOUNT
INSPE
OIL P
DOSAG
SEALI
FLYWH
INLET
TRANS
COVER
INJEC
SHUTT
KIT,
CYLIN
GEAR,
TRANS
SYNCH
EXHAU
FAN,
PIPE,
SEALI
SEALI
GASKE
PIPE,
GASKE
PRESS
EXPAN
SUPPO
SYNCH
SEALI
RADIA
CYLIN
ROCKE
SEALI
FAN,
IDLER
CRANK
TURBO
IDLER
SEAL,
SEALI
FAN H
EXHAU
TEMPE
SEALI
TURBO
PASS-
SEALI
COVER
SEALI
COPPE
EXPAN
CONTR
AIR V
CYLIN
SLEEV
SLEEV
SEALI
TURBO
TURBO
PIPE
PIPE
FAN,
EXHAU
EXHAU
SEALI
EXHAU
FAN,
FAN,
INJEC
COVER
GEARB
PRESS
VIBRA
DIPST
PUMP
COVER
COVER
SEALI
FLYWH
SEALI
FAN,
EXPAN
CHARG
CRANK
ROCKE
SENSO
COVER
CRANK
COVER
FAN H
IDLER
OIL F
EXHAU
THERM
COVER
TRANS
SEALI
EXHAU
TRANS
SEALI
SEALI
CYLIN
FLYWH
COVER
CHARG
COOLA
SEALI
FLANG
CHARG
CRANK
SENSO
SENSO
VIBRA
ROCKE
CHARG
GASKE
UNIT
COVER
TURBO
CYLIN
EXHAU
COMPA
LIP S
SENSO
SEALI
TRANS
PIPE
COMPA
CHARG
ROCKE
COVER
SEALI
ROCKE
SEALI
COVER
PASS-
DIAPH
FLYWH
ROCKE
NIPPL
FAN,
KIT,
SEALI
SEALI
DISC,
CYLIN
SEALI
COVER
VIBRA
SPRIN
PRESS
SEALI
SEALI
CRANK
CHARG
CYLIN
CYLIN
CRANK
PRESS
COVER
PIPE
ROCKE
BELT
IDLER
SEALI
BELT
IDLER
COVER
SEALI
UNIT
ROCKE
COVER
ROCKE
ROCKE
GASKE
FAN,
CHARG
EXHAU
IDLER
BELT
FAN,
IDLER
NEEDL
CONTR
ROCKE
GASKE
SLEEV
BELT
PISTO
CONTR
FAN,
AIR V
IDLER
COVER
SEALI
CONTR
CYLIN
PISTO
FAN,
EXHAU
SEALI
CONNE
EXHAU
TURBO
SUPPO
CYLIN
COVER
DUST
FLYWH
DIFFE
FAN,
BELT
ROCKE
SEALI
EXHAU
CHARG
DRIVE
SWITC
ROCKE
COVER
THERM
SUPPO
FAN H
AIR V
BELT
FAN H
FAN,
FAN,
ROCKE
FAN,
PRESS
PRESS
PIPE,
TIMIN
FLYWH
OIL P
CHARG
ROCKE
TRANS
CYLIN
TIMIN
OIL F
GROMM
PUMP
SEALI
SEALI
CHARG
CRANK
SENSO
HEXAG
PRESS
SEALI
SEALI
IDLER
TIMIN
IDLER
CRANK
PRESS
SLEEV
GASKE
CYLIN
THERM
O-RIN
COVER
EXHAU
TRANS
SENSO
COOLA
COVER
TURBO
EXHAU
COVER
OIL P
INJEC
TURBO
SYNCH
FAN,
CLUTC
CYLIN
CYLIN
FAN,
EXHAU
EXHAU
FAN,
MAIN
CYLIN
CYLIN
CYLIN
COVER
TURBO
CONTR
EXHAU
EXHAU
BELT
EXHAU
FLYWH
CYLIN
FAN,
CYLIN
EXHAU
AIR V
CAMSH
ROCKE
CYLIN
CABLE
DIPST
VALVE
IDLER
COPPE
EXHAU
CHARG
FAN,
CRANK
SEALI
SEALI
TURBO
GEARB
SERVI
BELT
SEALI
ROCKE
COVER
COVER
COVER
TRANS
COVER
EXHAU
BELT
COOLA
BELT
BELT
IDLER
BELT
COVER
COVER
COVER
FAN,
CLUTC
CYLIN
CYLIN
CYLIN
CYLIN
CYLIN
FAN,
FAN,
COVER
EXHAU
EXHAU
CLUTC
FAN,
FAN,
COVER
COVER
CYLIN
CYLIN
CLUTC
UNIT
CYLIN
CYLIN
CYLIN
EXHAU
EXHAU
COVER
EXHAU
EXHAU
CYLIN
BELT
CYLIN
FAN,
CYLIN
CYLIN
SEALI
SUPPO
EXHAU
EXHAU
CYLIN
COVER
SUPPO
TRANS
EXHAU
CYLIN
PUMP
EXHAU
EXHAU
COVER
CYLIN
SOFTW
GASKE
PIPE,
TIMIN
CRANK
GASKE
CYLIN
ROCKE
SEALI
CHARG
SENSO
THERM
SEALI
SOLEN
ROCKE
UNIT
SEALI
CRANK
SEALI
COVER
TURBO
SEALI
FLYWH
IDLER
CHARG
FLANG
FAN H
IDLER
BELT
COVER
SEALI
ENGAG
COVER
DIPST
COVER
OIL F
TRANS
COVER
SEALI
SEALI
EXHAU
COLLA
THERM
FAN,
CLUTC
FLYWH
CAMSH
ROCKE
ROCKE
IDLER
CLUTC
SENSO
AIR V
FAN,
EXHAU
EXPAN
COMPA
ROCKE
CONTR
IDLER
OIL P
COVER
COPPE
ROCKE
EXHAU
CRANK
OIL P
GEARB
COVER
FLYWH
TURBO
SEALI
RADIA
LIP S
SEALI
FLYWH
CHARG
CRANK
O-RIN
CYLIN
SEALI
CYLIN
COVER
CONVE
EXHAU
BELT
INJEC
CYLIN
SENSO
BELT
IDLER
TURBO
PRESS
COVER
PISTO
CLUTC
FAN H
INJEC
DRIVE
TURBO
PUMP
COVER
CYLIN
CYLIN
COVER
INJEC
SEALI
ENGIN
THERM
FAN,
EXPAN
PRESS
FLYWH
FAN,
THERM
SLEEV
PUMP
SEALI
FUEL
INJEC
FAN,
CAMSH
DIFFE
FAN,
SEALI
GASKE
PUMP
NEEDL
CYLIN
BELT
IDLER
FAN H
OIL P
CRANK
COVER
BELT
BELT
PRESS
BELT
IDLER
BELT
IDLER
BELT
COPPE
GASKE
TURBO
PRESS
COVER
IDLER
OIL P
PRESS
RADIA
BELT
PROPE
ROCKE
PRESS
SEALI
EXHAU
EXHAU
EXHAU
EXHAU
EXHAU
EXHAU
EXHAU
CRANK
ROCKE
DIFFE
TURBO
SUPPO
TURBO
CONTR
COPPE
LEAF
FLYWH
FAN,
KIT
PRESS
COVER
BELT
CONTR
COVER
GASKE
COPPE
THERM
SENSO
SEALI
BELT
BELT
IDLER
BELT
IDLER
IDLER
RADIA
OIL C
CONTR
SEALI
SEALI
SEALI
ROCKE
GEAR
SEALI
SEALI
COVER
FUEL
SENSO
DIAPH
SEALI
PIPE,
PULLE
SERVI
TURBO
PISTO
ROCKE
ROCKE
SEALI
DIFFE
ENGIN
SEALI
PUMP
SEALI
PUMP
CABLE
SLIDI
SUPPO
SEALI
SYNCH
FAN,
DIAPH
ROCKE
PROPE
PROPE
ROCKE
SEALI
SEALI
SENSO
COPPE
RADIA
INJEC
SEALI
GASKE
AIR V
TURBO
SEAL,
TURBO
SEALI
SLEEV
COVER
FLYWH
OIL P
CYLIN
CLUTC
CONTR
CYLIN
SEALI
FAN,
CLUTC
CRANK
SEALI
GASKE
SEALI
FLYWH
FAN,
KIT,
ROCKE
ROCKE
SEALI
CRANK
ROCKE
PRESS
PRESS
COOLA
CYLIN
OIL P
LIP S
BRACK
DIPST
AIR V
GASKE
COVER
COPPE
EXHAU
COVER
THERM
SOFTW
COPPE
ROCKE
PUMP
COVER
ROCKE
FAN,
CRANK
SEALA
SOFTW
COVER
CHARG
SEALI
BELT
CONTR
COVER
COVER
FAN,
INJEC
IDLER
TRANS
CONTR
SEALI
IDLER
BELT
EXHAU
EXHAU
CLUTC
INJEC
RADIA
SEALI
SEALI
SEALI
HOSE,
REPAI
INJEC
GASKE
BELT
CONTR
SYNCH
COVER
BELT
FLYWH
CYLIN
CRANK
GASKE
PUMP
SEALI
COVER
PASS-
SEALI
PUMP
SEALI
GASKE
OIL P
SLEEV
SEALI
SEALI
SEALI
TEMPE
CRANK
FAN H
EXPAN
CYLIN
RADIA
FAN,
FAN,
SENSO
PROPE
VALVE
SEALI
CYLIN
PRESS
CHARG
GASKE
INJEC
OIL P
CONTR
COOLA
GEARB
GEARB
SEALI
CABLE
OIL C
OIL C
PASS-
SEALI
PISTO
CLUTC
FAN,
EXHAU
SEALI
GASKE
PIPE
GASKE
COVER
EXHAU
CYLIN
SEALI
TURBO
COVER
TURBO
CYLIN
SEALI
ENGAG
THERM
PRESS
THRUS
PUMP
THERM
PISTO
GASKE
RING
BELT
PUMP
SEALI
BELT
EXHAU
CHARG
PROPE
SEALI
THERM
PROPE
PROPE
SEALI
INJEC
COVER
FAN,
IDLER
SEALI
KIT,
CONTR
PRESS
RADIA
TURBO
THERM
COOLA
PUMP
FAN,
EXHAU
PRESS
UNIT
OIL T
ROCKE
FAN,
SEALI
IDLER
IDLER
IDLER
ROCKE
SEALI
ROCKE
FAN,
CABLE
COVER
SERVI
CYLIN
ROCKE
CONTR
SOFTW
COVER
INLET
EXHAU
COVER
SEALI
CLUTC
FAN,
SEALI
V-CLA
CLUTC
ROCKE
CYLIN
FAN,
CRANK
PIPE,
PASS-
NEEDL
BELT
SOLEN
ROCKE
OIL P
COVER
COVER
COVER
BELT
RADIA
CRANK
CYLIN
PRESS
ROCKE
SEALI
COOLA
INLET
COMPA
DIPST
SEALI
TRANS
COVER
CYLIN
COVER
SENSO
CRANK
SEALI
FAN,
DIPST
COVER
O-RIN
LEAF
ROCKE
BRACK
BELT
HOSE,
HOSE,
EXHAU
CHARG
SEALI
KIT,
ROCKE
SEALI
V-CLA
ROCKE
CONTR
CHARG
PIPE,
CABLE
ROCKE
EXHAU
CYLIN
CYLIN
TRANS
EXHAU
ROCKE
PASS-
CLUTC
SEALI
SEALI
SEALI
PUMP
FLYWH
SEALI
DIPST
INJEC
RADIA
TRANS
SEALI
SENSO
FAN,
V-BEL
GEARB
TURBO
CAMSH
BELT
IDLER
EXHAU
SLEEV
DIAPH
SEALI
RADIA
FAN C
SEALI
ROCKE
BELT
SEALI
IDLER
GASKE
IDLER
PRESS
DIAPH
PASS-
CYLIN
SEALI
DIAPH
SEALI
IDLER
IDLER
CHARG
PIPE,
IDLER
ROCKE
GASKE
SOFTW
CYLIN
CONTR
ROCKE
TURBO
FAN,
V-CLA
ROCKE
COPPE
BELT
?
ROCKE
CYLIN
BELT
COVER
ROCKE
TURBO
TURBO
TURBO
ROCKE
CYLIN
CYLIN
CHARG
GASKE
CONTR
SEALI
GASKE
ROCKE
BELT
SEALI
SEALI
IDLER
DIAPH
PASS-
SEALI
SEALI
PIPE,
BELT
IDLER
DIFFE
GASKE
CAMSH
SHUTT
OIL L
BELT
SEALI
IDLER
TRANS
ROCKE
PIPE,
PRESS
ROCKE
PISTO
INJEC
CONTR
ROCKE
ROCKE
SOLEN
ROCKE
COVER
SLEEV
COVER
TURBO
COVER
PIPE
OIL P
CYLIN
V-BEL
DIPST
PUMP
TEMPE
SLEEV
CONTR
CYLIN
BELT
SOLEN
BRACK
ROCKE
FAN,
COOLA
SLEEV
TURBO
COVER
TURBO
PRESS
SLEEV
FAN,
TIMIN
SEALI
FAN,
INJEC
ROCKE
SEAL,
CRANK
CHARG
SEALI
CONTR
CHARG
SERVI
CHARG
HOUSI
SOLEN
FAN,
CONNE
BELT
SENSO
GASKE
FAN,
IDLER
ROCKE
CRANK
COVER
TURBO
BELT
INJEC
COVER
SEALI
INJEC
TURBO
PRESS
CLUTC
FAN,
ROCKE
ROCKE
VALVE
VALVE
OIL P
EXHAU
PRESS
ROCKE
SEALI
CHARG
SEALI
PUMP
FAN,
SLEEV
SEALI
SEALI
SEALI
IDLER
BELT
THERM
TURBO
TEMPE
TURBO
GASKE
CHARG
PRESS
PRESS
ROCKE
ROCKE
SEALI
SEALI
CHARG
CYLIN
ROCKE
COMPA
COVER
THERM
COOLA
CRANK
ROCKE
PASS-
CONTR
DIAPH
ROCKE
SEALA
ROCKE
DIAPH
SEALI
SEALI
FAN,
THERM
GASKE
GASKE
ROCKE
RADIA
FAN,
FAN,
BELT
IDLER
CLUTC
CHARG
SEALI
SEALI
SOFTW
GASKE
BELT
GASKE
BELT
IDLER
EXHAU
EXHAU
AIR V
O-RIN
ROCKE
INSEC
CHARG
SEALI
SEALI
GASKE
?
TURBO
GASKE
SHUTT
OIL L
COVER
ROCKE
COVER
SEALI
FLYWH
BRACK
FAN,
SEALI
COOLA
CYLIN
OIL C
BELT
CYLIN
TURBO
PASS-
THERM
PISTO
CLUTC
SOFTW
COVER
ROCKE
SOLEN
CYLIN
VALVE
SENSO
INJEC
PISTO
CYLIN
GASKE
ENGAG
BRACK
THERM
BELT
BELT
IDLER
BELT
ROCKE
COVER
COVER
TRANS
CYLIN
CYLIN
TURBO
COVER
SLEEV
CYLIN
CRANK
CYLIN
ROCKE
SEALI
COVER
COVER
FAN C
EXHAU
SEALI
COVER
CYLIN
PUMP
AIR V
TEMPE
DIAPH
SEALI
SEALI
GASKE
TRANS
DIFFE
TURBO
INLET
CYLIN
COVER
CYLIN
COVER
CYLIN
UNIT
SEALI
CONTR
DIFFE
GEAR,
SOFTW
CABLE
SERVI
UNIT
CRANK
BELT
SEALA
OVERF
BELT
SEALI
BELT
TURBO
SEALI
COVER
DRIVE
TORQU
CYLIN
CLUTC
ROCKE
COVER
FAN,
LIP S
CYLIN
RADIA
SEALI
CABLE
CABLE
FAN,
CHARG
SEALI
EXHAU
ROCKE
GASKE
FLYWH
CONTR
PASS-
GASKE
THERM
PRESS
SEALI
SEALI
COVER
SHIM,
ROCKE
PRESS
ROCKE
CYLIN
CONTR
COVER
PRESS
COVER
GASKE
SEALI
FUEL
CYLIN
CLUTC
CYLIN
CYLIN
CYLIN
SLEEV
COPPE
SENSO
FAN,
SERVI
CRANK
ROCKE
CYLIN
CRANK
COVER
EXHAU
TRANS
FAN,
COVER
CRANK
COOLA
COVER
FAN,
SEALI
CRANK
PUMP
PRESS
CHARG
HOUSI
FAN,
BELT
CAMSH
SEALI
AIR V
SEALI
SEAL,
FAN,
V-BEL
SEALI
COPPE
ROCKE
CAGE,
FAN,
SEALI
INLET
COVER
GASKE
CYLIN
INJEC
COVER
TURBO
SHIM,
COVER
DIAPH
FLANG
PASS-
DIPST
FAN,
UNIT
FLANG
GASKE
CYLIN
CHARG
IDLER
COVER
PRESS
OIL L
GASKE
LIP S
SEALI
ROCKE
BELT
RING
CRANK
GASKE
DIAPH
SEALI
ROCKE
IDLER
BELT
GASKE
GASKE
GASKE
CHARG
PRESS
COVER
GASKE
GASKE
ROCKE
ROCKE
GASKE
ROCKE
GASKE
PLUG
COVER
CYLIN
CYLIN
FLYWH
CRANK
COVER
COVER
FAN H
COPPE
TRANS
TRANS
CRANK
FUEL
TEMPE
TURBO
INJEC
SEALI
PRESS
VALVE
INJEC
TURBO
TURBO
SEALI
COVER
COVER
THERM
COVER
CYLIN
SOLEN
AIR V
FAN H
FAN,
DIAPH
CYLIN
CHARG
SLEEV
CYLIN
OIL P
CRANK
SEALI
DIAPH
SEALI
IDLER
PRESS
OVERF
BELT
CHARG
DEFLE
COVER
ROCKE
CONTR
BELT
SEALI
BELT
CYLIN
TURBO
SEALI
COVER
INLET
SEALI
VALVE
COVER
COVER
COVER
SEALI
COMPA
CHARG
SEALI
LEAF
THERM
GASKE
CYLIN
INPUT
COVER
STOP
BELT
COVER
SERVI
CLUTC
PISTO
COVER
AIR I
ROCKE
TRANS
BELT
COOLA
COVER
COVER
COVER
CYLIN
FAN,
CLUTC
PIPE
GASKE
GASKE
SEALI
FAN,
SOFTW
EXHAU
COPPE
CONTR
FAN,
CYLIN
COVER
KIT
EXHAU
BELT
OIL F
THERM
RADIA
FAN,
SEALI
PIPE,
GASKE
COVER
SOLEN
ROCKE
CYLIN
BELT
BELT
SEALI
SEALI
COOLA
FLYWH
CYLIN
GEARB
SEALI
CHARG
EXHAU
BELT
IDLER
CRANK
TEMPE
GASKE
COPPE
SEALI
COVER
V-CLA
SEALI
PRESS
CLAMP
THERM
LIP S
GASKE
PLANE
COMPA
SEALA
V-BEL
SPRIN
CRANK
PIPE,
IDLER
ROLLE
SEAL,
CYLIN
GASKE
COVER
COVER
COVER
GASKE
GASKE
ROCKE
ROCKE
ROCKE
CHARG
BELT
CRANK
CAMSH
ROCKE
COVER
FAN,
TIMIN
SEALI
CYLIN
FLYWH
CLUTC
TIMIN
O-RIN
COVER
COVER
SEALI
THERM
COVER
CHARG
BELT
IDLER
SYNCH
CYLIN
SERVI
SEALI
CONNE
SEALI
FAN,
BELT
IDLER
LIP S
PASS-
BELT
BELT
CHARG
THERM
TEMPE
IDLER
TURBO
CYLIN
TIMIN
SOFTW
FILTE
COVER
SOLEN
PROPE
PRESS
INLET
COVER
SEALI
CAMSH
GEAR,
CYLIN
COVER
TECU/
CRANK
AIR V
TIMIN
CYLIN
CLAMP
PUMP
COVER
PUMP
CYLIN
FUEL
SOFTW
FAN,
GEARB
CYLIN
COVER
SOLEN
FAN,
GASKE
V-CLA
SEALI
LIP S
CRANK
BELT
NEEDL
COVER
COVER
IDLER
CAMSH
CYLIN
COVER
OIL F
ROCKE
SPRIN
V-BEL
CONTR
GEAR,
CYLIN
EXHAU
SEALI
SERVI
EXHAU
DIFFE
CONTR
CAMSH
BELT
COVER
CRANK
AIR V
INJEC
SOLEN
EXPAN
SERVI
FUEL
AIR V
TRANS
TURBO
TURBO
CYLIN
SEALI
COPPE
O-RIN
CLUTC
GASKE
AIR V
PRESS
TECU/
BRACK
SHUTT
UNIT
INJEC
CRANK
SEALI
VALVE
CLUTC
GEAR
AIR V
FAN,
FAN,
COVER
SENSO
FAN,
EXPAN
CRANK
SEALI
SEALI
PASS-
SERVI
GASKE
COPPE
PIPE,
SEALI
IDLER
GASKE
PASS-
SEALI
INJEC
CHARG
TEMPE
SOFTW
PASS-
UNIT
CONTR
CHARG
SEALI
BELT
CONTR
THERM
PRESS
COVER
CLUTC
CYLIN
GEARB
CYLIN
COPPE
UNIT
SHUTT
SEALI
CYLIN
V-CLA
INJEC
V-BEL
COVER
SEALI
CAMSH
COVER
BELT
INJEC
SEALI
SERVI
TURBO
CRANK
COVER
UNIT
OIL F
CRANK
COVER
COVER
INJEC
INJEC
COVER
SEALI
CRANK
CRANK
FUEL
PRESS
CYLIN
IDLER
CYLIN
CYLIN
PASS-
OIL P
COVER
SEALI
COVER
BELT
GASKE
SEALI
CYLIN
COVER
OIL P
COVER
GASKE
CAMSH
INJEC
CHARG
COVER
COVER
CYLIN
COVER
CONTR
GASKE
NUT R
SEAL,
PISTO
LIP S
PASS-
COVER
TEMPE
CYLIN
COVER
FLYWH
PRESS
UNIT
SEALI
FAN,
CAMSH
CRANK
THRUS
UNIT
COVER
BELT
COPPE
TURBO
FLYWH
COVER
SLEEV
COVER
IDLER
IDLER
COVER
COVER
COVER
COVER
CYLIN
CYLIN
CYLIN
INJEC
OIL L
CRANK
PIPE,
DIPST
CRANK
SEALI
CRANK
COVER
TURBO
SEALI
SEALI
PASS-
BELT
ROCKE
RADIA
OIL C
BELT
IDLER
EXHAU
SYNCH
SOFTW
ROCKE
PASS-
EXHAU
PRESS
FAN,
CYLIN
SENSO
PASS-
CRANK
CAMSH
INJEC
EXPAN
CAMSH
SEALI
INJEC
BELT
FILTE
FAN,
AIR V
OIL L
FAN,
AIR V
GASKE
THERM
IDLER
BELT
GROMM
THERM
PRESS
SEALI
ENGAG
TURBO
CRANK
INJEC
INJEC
INJEC
INJEC
CONTR
UNIT
VALVE
CLUTC
FLYWH
INJEC
FLYWH
PISTO
IDLER
TIMIN
CYLIN
IDLER
DIAPH
VALVE
CONTR
FLYWH
GASKE
ADJUS
COVER
IDLER
BELT
FLYWH
LEAF
SERVI
BELT
IDLER
BELT
COPPE
CYLIN
PRESS
INJEC
SYNCH
INJEC
PASS-
GASKE
SEALI
PRESS
SENSO
CYLIN
PRESS
AIR V
SERVI
COPPE
CRANK
GASKE
CHARG
COMPA
COVER
SEALI
CHARG
COPPE
EXPAN
FLYWH
SEALI
COVER
EXHAU
COPPE
COPPE
GASKE
SEALI
PIPE
DIPST
CRANK
GEARB
SOFTW
EXPAN
CONNE
LIP S
COVER
OIL F
COVER
HOSE,
TRANS
FAN,
SEALI
GEARB
COVER
PISTO
PRESS
TURBO
INJEC
INJEC
COVER
CYLIN
CYLIN
GASKE
SEALI
COPPE
SYNCH
CYLIN
CYLIN
FAN,
SEALI
SEALI
GEARB
FAN,
SEALI
SERVI
BELT
COVER
SENSO
COVER
INJEC
CHARG
SENSO
FAN,
RADIA
OIL T
OIL T
OIL T
COVER
PIPE,
GASKE
COVER
REPAI
CONTR
PRESS
TURBO
BUSHI
COMPA
LIP S
BELT
UNIT
ROCKE
SERVI
SEALI
V-CLA
AIR V
GEAR,
CYLIN
THERM
COPPE
COOLA
CAMSH
CYLIN
SEALI
FAN,
COVER
CYLIN
CYLIN
FAN,
EXHAU
SEALI
SEALI
PRESS
CYLIN
CRANK
IDLER
IDLER
CYLIN
CYLIN
PASS-
PRESS
PIPE
CYLIN
SEALI
SENSO
SLEEV
PRESS
GASKE
SEALI
COVER
PASS-
LIP S
BELT
IDLER
SEALI
SEALI
CRANK
IDLER
CYLIN
SEALI
DIAPH
SEALI
CHARG
BELT
EXPAN
PASS-
SEALI
SEALI
THERM
SEALI
CRANK
SEALI
BELT
IDLER
GASKE
PASS-
CYLIN
CYLIN
SYNCH
CAMSH
FLYWH
GASKE
SEALI
SEALI
SEALI
OIL P
SEALI
PLATE
COPPE
VALVE
OVERF
COVER
CYLIN
ROLLE
AIR V
NEEDL
CONTR
CYLIN
CYLIN
CRANK
IDLER
IDLER
SEALI
BELT
INJEC
SEALI
TIMIN
EXHAU
CYLIN
CHARG
TECU/
CRANK
GEAR
CLUTC
COPPE
CONTR
THERM
IDLER
NIPPL
EXPAN
CAMSH
BELT
INJEC
NUT R
COVER
COVER
EXHAU
CONTR
COVER
FAN,
SEALI
GASKE
COVER
COPPE
TURBO
PIPE,
CRANK
TURBO
GEAR,
COVER
EXHAU
OIL P
EXHAU

In [7]:
#第二种
for n in df.itertuples():
    print(n)
    break

Pandas(Index=0, _1=7982280, _2=nan, _3='10/08/2015', _4=490233.0, State='QLD', _6=1.0, _7='FH13 64T', _8=nan, _9=85003217, _10='CYLINDER HEAD, EXCH, SPARE PART', _11=2111, _12=nan, _13=135216, _14=nan, _15=653344, _16=nan, _17=1430.28, _18=5939.73, _19=0.0, _20=7370.01, Total_Payment=7370.01, Company=nan, _23=nan, _24=42250, _25=9, _26=42248, Model_='FH13', Year=2015, if_model_same_with_prev_row='previous row not exist')

In [8]:
for n in df.itertuples():
    print(n[5])

QLD
NSW
VIC
SA
WA
WA
NSW
QLD
NSW
NSW
VIC
SA
WA
NSW
NSW
QLD
WA
QLD
SA
NSW
WA
QLD
QLD
VIC
VIC
SA
WA
WA
VIC
WA
WA
TA
WA
QLD
WA
WA
QLD
WA
QLD
WA
WA
WA
WA
NSW
NSW
SA
WA
VIC
VIC
VIC
QLD
WA
WA
SA
SA
SA
SA
WA
WA
WA
WA
WA
VIC
VIC
VIC
SA
SA
NSW
NSW
NSW
WA
VIC
VIC
VIC
NSW
NSW
NSW
NSW
NSW
NSW
SA
SA
SA
SA
SA
NSW
NSW
NSW
WA
WA
NSW
SA
SA
VIC
QLD
QLD
QLD
SA
SA
SA
QLD
SA
SA
VIC
VIC
QLD
WA
WA
NSW
NSW
NSW
NSW
VIC
VIC
WA
WA
WA
WA
WA
WA
NSW
VIC
VIC
VIC
QLD
WA
QLD
NSW
QLD
QLD
SA
WA
NSW
NSW
SA
VIC
WA
SA
SA
SA
WA
SA
NSW
SA
SA
SA
SA
SA
SA
NSW
QLD
WA
WA
WA
WA
WA
NSW
NSW
NSW
NSW
SA
WA
TA
TA
WA
WA
WA
VIC
SA
SA
WA
WA
WA
WA
VIC
NSW
VIC
SA
SA
WA
SA
NSW
WA
WA
WA
VIC
VIC
VIC
SA
NSW
QLD
SA
VIC
VIC
NSW
NSW
NSW
QLD
SA
WA
NSW
NSW
WA
QLD
WA
WA
SA
SA
SA
NSW
NSW
NSW
WA
NSW
NSW
QLD
NSW
NSW
NSW
WA
WA
WA
VIC
VIC
QLD
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
NSW
NSW
WA
SA
WA
WA
NSW
NSW
SA
NSW
QLD
QLD
QLD
WA
WA
WA
WA
WA
WA
WA
WA
QLD
QLD
SA
WA
WA
QLD
QLD
QLD
QLD
QLD
WA
QLD
WA
WA
QLD
NSW
NSW
SA
WA
SA
WA
WA
WA
WA
WA
NSW
NSW
WA
WA
WA
VIC
NSW
NSW
QLD
VIC
SA
SA
SA
SA
NSW
NSW
SA
SA
SA
SA
NSW
SA
SA
NSW
WA
WA
SA
QLD
NSW
NSW
NSW
NSW
WA
WA
WA
WA
WA
WA
VIC
VIC
VIC
VIC
VIC
VIC
SA
WA
SA
NSW
NSW
NSW
SA
SA
NSW
NSW
SA
NSW
NSW
WA
VIC
SA
SA
SA
SA
SA
SA
NSW
SA
SA
SA
SA
SA
SA
SA
SA
SA
WA
WA
SA
WA
WA
WA
WA
WA
SA
SA
NSW
SA
NSW
WA
WA
WA
WA
WA
QLD
WA
SA
QLD
TA
WA
SA
SA
NSW
QLD
QLD
QLD
WA
QLD
QLD
WA
TA
QLD
QLD
QLD
QLD
QLD
QLD
VIC
VIC
VIC
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
NSW
NSW
NSW
NSW
QLD
VIC
VIC
VIC
VIC
WA
WA
VIC
VIC
VIC
WA
WA
WA
NSW
NSW
NSW
NSW
SA
VIC
VIC
SA
SA
QLD
WA
WA
WA
QLD
VIC
WA
SA
SA
NSW
NSW
SA
VIC
SA
SA
VIC
NSW
SA
SA
SA
SA
SA
SA
WA
WA
WA
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
NSW
QLD
QLD
QLD
QLD
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
SA
SA
QLD
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
QLD
QLD
QLD
QLD
QLD
VIC
VIC
VIC
QLD
QLD
QLD
QLD
QLD
QLD
QLD
WA
WA
WA
WA
NSW
WA
WA
NSW
NSW
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
QLD
VIC
VIC
VIC
QLD
QLD
QLD
QLD
WA
NSW
QLD
QLD
QLD
WA
SA
VIC
NSW
SA
VIC
VIC
WA
NSW
WA
NSW
NSW
NSW
NSW
SA
SA
SA
SA
WA
VIC
SA
SA
WA
WA
WA
VIC
WA
SA
SA
SA
SA
SA
SA
SA
NSW
SA
NSW
NSW
NSW
QLD
VIC
VIC
VIC
VIC
WA
WA
QLD
NSW
VIC
VIC
VIC
WA
SA
SA
SA
QLD
QLD
SA
NSW
WA
SA
SA
QLD
QLD
NSW
NSW
NSW
SA
SA
SA
SA
VIC
QLD
QLD
SA
SA
SA
SA
SA
NSW
NSW
QLD
WA
SA
WA
WA
WA
SA
WA
WA
QLD
QLD
QLD
QLD
VIC
VIC
SA
SA
WA
VIC
SA
NSW
NSW
WA
QLD
WA
SA
SA
QLD
SA
NSW
WA
QLD
WA
WA
WA
SA
WA
WA
WA
WA
SA
VIC
SA
WA
VIC
SA
NSW
SA
QLD
VIC
QLD
QLD
QLD
SA
QLD
QLD
QLD
QLD
QLD
WA
WA
VIC
WA
QLD
SA
QLD
QLD
SA
NSW
NSW
VIC
QLD
VIC
QLD
QLD
SA
SA
SA
SA
SA
NSW
QLD
QLD
QLD
QLD
QLD
QLD
SA
QLD
WA
QLD
SA
QLD
QLD
QLD
NSW
SA
NSW
NSW
NSW
WA
WA
WA
SA
VIC
VIC
WA
WA
VIC
QLD
NSW
NSW
SA
SA
SA
NSW
SA
SA
WA
SA
SA
SA
WA
WA
WA
SA
WA
WA
WA
WA
WA
WA
SA
SA
QLD
SA
WA
WA
WA
SA
SA
WA
WA
WA
WA
WA
SA
SA
WA
QLD
NSW
VIC
VIC
SA
SA
WA
WA
NSW
QLD
QLD
VIC
SA
WA
QLD
NSW
NSW
QLD
SA
WA
WA
WA
VIC
VIC
VIC
VIC
VIC
VIC
VIC
VIC
VIC
NSW
NSW
NSW
NSW
NSW
QLD
SA
SA
SA
QLD
SA
WA
WA
WA
WA
SA
SA
SA
SA
SA
QLD
WA
NSW
NSW
NSW
SA
SA
QLD
SA
SA
WA
QLD
QLD
QLD
QLD
WA
WA
VIC
WA
SA
NSW
WA
SA
NSW
QLD
QLD
WA
WA
WA
WA
SA
SA
WA
QLD
NSW
WA
VIC
SA
SA
WA
QLD
QLD
SA
NSW
SA
WA
NSW
NSW
SA
WA
NSW
NSW
NSW
WA
WA
WA
SA
SA
SA
WA
SA
SA
WA
NSW
NSW
NSW
WA
WA
SA
SA
QLD
WA
WA
WA
QLD
NSW
NSW
NSW
NSW
SA
QLD
WA
WA
WA
SA
SA
TA
WA
WA
NSW
NSW
WA
WA
WA
WA
SA
QLD
TA
WA
QLD
WA
WA
QLD
SA
SA
SA
QLD
WA
SA
NSW
WA
SA
SA
SA
VIC
VIC
WA
VIC
SA
TA
WA
NSW
SA
SA
QLD
SA
SA
SA
WA
TA
VIC
SA
NSW
NSW
SA
WA
WA
WA
WA
WA
WA
SA
VIC
SA
SA
SA
SA
SA
NSW
WA
SA
SA
NSW
NSW
NSW
VIC
SA
SA
SA
SA
QLD
SA
VIC
SA
QLD
WA
VIC
VIC
SA
SA
VIC
VIC
WA
NSW
NSW
WA
WA
SA
SA
SA
SA
WA
SA
WA
WA
WA
WA
WA
WA
WA
QLD
QLD
QLD
SA
QLD
QLD
QLD
QLD
VIC
VIC
NSW
WA
WA
WA
WA
VIC
WA
WA
WA
WA
WA
SA
SA
QLD
VIC
WA
QLD
QLD
NSW
WA
WA
WA
WA
NSW
NSW
WA
SA
QLD
QLD
VIC
SA
SA
NSW
VIC
WA
NSW
QLD
WA
QLD
QLD
WA
QLD
NSW
SA
QLD
WA
WA
WA
SA
VIC
NSW
NSW
SA
SA
QLD
NSW
WA
QLD
QLD
VIC
NSW
WA
SA
SA
WA
SA
SA
SA
SA
SA
SA
SA
SA
VIC
VIC
VIC
QLD
QLD
WA
NSW
QLD
QLD
QLD
SA
WA
SA
SA
WA
NSW
WA
VIC
QLD
WA
QLD
QLD
SA
WA
WA
WA
WA
QLD
QLD
WA
WA
WA
NSW
NSW
NSW
WA
SA
VIC
VIC
VIC
SA
SA
WA
WA
SA
SA
SA
WA
SA
SA
VIC
SA
WA
WA
WA
WA
NSW
NSW
SA
QLD
SA
SA
SA
NSW
NSW
WA
SA
VIC
QLD
SA
WA
SA
WA
QLD
QLD
SA
WA
WA
WA
VIC
WA
VIC
NSW
NSW
NSW
NSW
SA
NSW
WA
SA
WA
WA
SA
SA
SA
NSW
WA
WA
WA
WA
WA
WA
WA
NSW
WA
VIC
SA
NSW
NSW
NSW
NSW
NSW
SA
SA
SA
SA
TA
VIC
QLD
VIC
VIC
VIC
NSW
NSW
NSW
NSW
NSW
NSW
NSW
SA
SA
WA
NSW
WA
QLD
NSW
SA
SA
SA
QLD
SA
SA
SA
SA
WA
WA
SA
QLD
QLD
VIC
VIC
QLD
QLD
QLD
SA
WA
VIC
VIC
VIC
QLD
NSW
NSW
NSW
NSW
QLD
QLD
WA
WA
WA
NSW
NSW
SA
SA
SA
SA
VIC
QLD
NSW
QLD
QLD
SA
WA
SA
VIC
VIC
SA
SA
VIC
NSW
SA
WA
NSW
QLD
WA
QLD
WA
WA
SA
SA
SA
SA
SA
SA
SA
QLD
WA
SA
SA
SA
SA
SA
SA
WA
SA
SA
SA
SA
WA
NSW
NSW
QLD
WA
WA
WA
WA
SA
NSW
WA
WA
WA
QLD
SA
SA
NSW
VIC
VIC
VIC
SA
SA
WA
VIC
VIC
WA
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
NSW
NSW
SA
SA
SA
QLD
VIC
VIC
NSW
NSW
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
WA
WA
QLD
WA
WA
SA
SA
NSW
SA
SA
VIC
SA
SA
QLD
VIC
VIC
NSW
SA
SA
WA
SA
SA
SA
SA
SA
NSW
QLD
WA
QLD
NSW
NSW
WA
WA
WA
NSW
NSW
NSW
WA
NSW
SA
SA
SA
SA
NSW
NSW
SA
SA
SA
WA
SA
SA
SA
SA
SA
SA
NSW
NSW
NSW
QLD
NSW
WA
WA
SA
SA
SA
WA
WA
QLD
NSW
SA
QLD
QLD
QLD
WA
WA
WA
WA
WA
WA
SA
SA
NSW
QLD
WA
VIC
NSW
WA
WA
WA
WA
WA
WA
QLD
QLD
SA
VIC
VIC
WA
SA
SA
NSW
SA
NSW
QLD
SA
WA
SA
SA
SA
WA
WA
SA
SA
SA
WA
WA
NSW
SA
SA
WA
WA
WA
SA
QLD
NSW
QLD
WA
WA
WA
WA
SA
SA
SA
SA
NSW
SA
SA
SA
QLD
NSW
WA
SA
SA
SA
WA
SA
SA
SA
SA
SA
SA
NSW
WA
SA
SA
SA
WA
WA
QLD
NSW
WA
WA
SA
SA
WA
SA
SA
NSW
SA
WA
SA
SA
WA
SA
QLD
QLD
QLD
WA
WA
NSW
SA
SA
SA
SA
WA
WA
SA
WA
QLD
WA
WA
SA
WA
NSW
NSW
SA
WA
VIC
SA
NSW
NSW
NSW
QLD
WA
SA
SA
NSW
SA
QLD
NSW
WA
QLD
WA
WA
WA
VIC
SA
SA
SA
WA
WA
QLD
QLD
SA
WA
SA
SA
SA
SA
QLD
NSW
NSW
SA
WA
WA
SA
SA
SA
SA
WA
WA
WA
SA
SA
SA
SA
SA
WA
WA
SA
NSW
SA
NSW
SA
SA
WA
WA
NSW
VIC
SA
SA
SA
WA
QLD
QLD
QLD
WA
WA
SA
WA
VIC
VIC
VIC
VIC
WA
SA
SA
SA
SA
SA
SA
NSW
NSW
NSW
NSW
SA
SA
WA
SA
QLD
QLD
QLD
QLD
QLD
WA
NSW
VIC
SA
SA
WA
WA
WA
WA
NSW
SA
NSW
QLD
SA
SA
WA
WA
WA
VIC
SA
NSW
NSW
VIC
SA
SA
QLD
QLD
NSW
WA
NSW
NSW
SA
SA
QLD
WA
SA
QLD
QLD
SA
QLD
WA
SA
WA
VIC
WA
QLD
WA
QLD
WA
WA
WA
WA
VIC
SA
NSW
SA
SA
SA
SA
SA
SA
SA
SA
WA
SA
WA
WA
NSW
WA
WA
QLD
SA
SA
SA
SA
WA
WA
QLD
WA
SA
WA
WA
NSW
SA
SA
WA
WA
NSW
SA
WA
WA
QLD
QLD
WA
QLD
WA
WA
WA
WA
VIC
WA
VIC
SA
SA
QLD
TA
SA
WA
SA
WA
QLD
SA
QLD
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
WA
WA
WA
WA
SA
SA
TA
SA
SA
QLD
SA
WA
QLD
NSW
WA
WA
VIC
WA
SA
SA
WA
WA
QLD
SA
SA
QLD
NSW
SA
WA
WA
SA
SA
NSW
WA
WA
SA
QLD
SA
SA
WA
WA
VIC
SA
SA
SA
SA
SA
WA
SA
QLD
NSW
VIC
SA
SA
VIC
VIC
VIC
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
NSW
NSW
NSW
VIC
WA
QLD
WA
WA
WA
WA
WA
WA
SA
SA
NSW
VIC
WA
SA
QLD
QLD
NSW
NSW
WA
WA
WA
NSW
NSW
WA
WA
SA
SA
SA
NSW
WA
SA
VIC
SA
VIC
WA
SA
SA
VIC
TA
WA
SA
SA
SA
SA
SA
SA
WA
NSW
NSW
NSW
WA
WA
WA
SA
SA
QLD
WA
WA
WA
SA
SA
WA
WA
WA
SA
SA
SA
TA
SA
SA
SA
SA
SA
VIC
WA
SA
SA
VIC
NSW
WA
VIC
SA
NSW
QLD
QLD
QLD
WA
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
VIC
NSW
VIC
VIC
QLD
SA
SA
SA
WA
WA
WA
WA
WA
WA
QLD
SA
SA
SA
SA
SA
WA
NSW
NSW
WA
VIC
VIC
SA
VIC
SA
SA
WA
WA
SA
SA
QLD
NSW
QLD
QLD
WA
VIC
VIC
SA
VIC
SA
SA
SA
SA
SA
SA
WA
NSW
NSW
NSW
SA
SA
SA
SA
NSW
WA
SA
SA
WA
WA
WA
WA
WA
WA
SA
NSW
VIC
QLD
SA
SA
VIC
QLD
QLD
SA
SA
SA
SA
SA
SA
WA
WA
WA
QLD
WA
WA
WA
WA
SA
SA
SA
NSW
NSW
WA
WA
VIC
WA
QLD
WA
WA
WA
WA
WA
WA
SA
QLD
SA
NSW
WA
WA
WA
WA
WA
WA
VIC
WA
TA
SA
WA
SA
WA
WA
QLD
VIC
QLD
NSW
SA
WA
WA
WA
WA
SA
WA
WA
WA
SA
TA
WA
WA
SA
SA
NSW
WA
WA
SA
WA
VIC
WA
WA
SA
SA
SA
SA
SA
QLD
QLD
NSW
WA
NSW
VIC
VIC
WA
WA
WA
VIC
SA
SA
SA
SA
NSW
WA
WA
WA
QLD
TA
SA
SA
WA
WA
NSW
QLD
NSW
WA
WA
WA
WA
WA
SA
SA
NSW
SA
SA
SA
VIC
SA
NSW
SA
SA
SA
WA
WA
WA
WA
SA
SA
WA
WA
QLD
QLD
SA
SA
SA
SA
QLD
QLD
SA
SA
SA
SA
NSW
SA
WA
QLD
TA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
WA
SA
WA
WA
VIC
SA
QLD
WA
VIC
WA
WA
WA
QLD
SA
VIC
WA
SA
SA
SA
WA
QLD
QLD
QLD
TA
WA
WA
SA
VIC
VIC
SA
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
QLD
NSW
WA
WA
WA
QLD
SA
SA
SA
WA
SA
WA
WA
NSW
WA
WA
NSW
QLD
WA
VIC
WA
SA
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
WA
NSW
NSW
NSW
SA
SA
WA
WA
SA
SA
VIC
WA
WA
WA
WA
WA
QLD
QLD
WA
SA
WA
WA
WA
SA
SA
WA
WA
SA
SA
QLD
QLD
NSW
NSW
NSW
QLD
QLD
SA
WA
SA
WA
TA
WA
SA
NSW
VIC
SA
NSW
QLD
QLD
NSW
WA
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
WA
WA
WA
NSW
SA
SA
SA
WA
WA
WA
NSW
WA
SA
SA
SA
SA
SA
SA
WA
WA
WA
WA
WA
WA
SA
WA
WA
NSW
NSW
WA
SA
VIC
VIC
WA
VIC
WA
SA
SA
SA
SA
WA
QLD
VIC
VIC
NSW
SA
SA
SA
SA
SA
SA
SA
WA
VIC
WA
WA
SA
WA
NSW
VIC
QLD
NSW
WA
WA
QLD
WA
VIC
WA
VIC
VIC
SA
VIC
QLD
SA
QLD
SA
NSW
NSW
WA
NSW
WA
SA
WA
WA
SA
WA
WA
WA
WA
WA
VIC
VIC
SA
WA
SA
WA
NSW
NSW
NSW
SA
QLD
SA
SA
QLD
SA
SA
WA
WA
WA
QLD
QLD
QLD
WA
NSW
SA
SA
NSW
SA
WA
WA
SA
SA
SA
WA
SA
WA
SA
QLD
QLD
VIC
NSW
SA
NSW
QLD
QLD
QLD
SA
NSW
WA
WA
WA
VIC
SA
WA
NSW
SA
WA
QLD
WA
SA
SA
WA
SA
SA
NSW
NSW
WA
WA
SA
SA
QLD
SA
NSW
WA
WA
VIC
WA
SA
WA
WA
WA
WA
VIC
QLD
QLD
WA
VIC
TA
SA
WA
VIC
WA
SA
WA
WA
WA
SA
NSW
QLD
SA
SA
SA
TA
QLD
SA
NSW
SA
SA
SA
SA
SA
SA
SA
WA
SA
SA
WA
SA
SA
SA
SA
SA
QLD
QLD
WA
QLD
QLD
QLD
WA
WA
WA
WA
SA
SA
WA
QLD
SA
TA
SA
SA
SA
NSW
WA
TA
QLD
SA
QLD
QLD
SA
TA
SA
SA
SA
SA
WA
WA
WA
WA
SA
SA
SA
SA
VIC
VIC
SA
SA
SA
SA
SA
SA
SA
SA
WA
SA
WA
SA
VIC
SA
WA
SA
SA
TA
QLD
QLD
SA
SA
QLD
QLD
QLD
QLD
QLD
WA
QLD
QLD
QLD
WA
WA
WA
VIC
QLD
QLD
QLD
QLD
SA
WA
SA
VIC
WA
SA
WA
WA
SA
SA
SA
SA
SA
SA
SA
WA
WA
WA
WA
WA
NSW
WA
SA
SA
SA
SA
SA
WA
WA
WA
QLD
SA
SA
SA
WA
WA
SA
SA
SA
SA
SA
SA
WA
WA
NSW
NSW
NSW
SA
SA
SA
QLD
WA
SA
SA
SA
WA
SA
WA
WA
VIC
VIC
VIC
SA
SA
SA
SA
QLD
SA
SA
WA
NSW
SA
SA
SA
SA
SA
SA
SA
WA
SA
WA
QLD
QLD
QLD
QLD
QLD
QLD
WA
VIC
VIC
QLD
QLD
QLD
SA
SA
VIC
WA
WA
WA
SA
WA
WA
WA
SA
SA
WA
WA
QLD
WA
WA
SA
NSW
NSW
WA
WA
WA
WA
WA
SA
QLD
WA
WA
NSW
SA
SA
TA
SA
SA
SA
WA
WA
WA
SA
NSW
NSW
SA
SA
SA
WA
WA
WA
WA
SA
TA
NSW
NSW
SA
NSW
SA
SA
NSW
WA
SA
WA
SA
SA
QLD
QLD
QLD
NSW
QLD
SA
SA
SA
SA
VIC
SA
TA
QLD
WA
WA
SA
SA
SA
WA
SA
SA
WA
WA
NSW
SA
SA
SA
SA
SA
TA
SA
QLD
QLD
SA
SA
SA
NSW
WA
SA
SA
NSW
WA
WA
QLD
NSW
WA
VIC
VIC
QLD
WA
WA
WA
WA
NSW
NSW
SA
QLD
QLD
QLD
SA
SA
NSW
SA
QLD
QLD
WA
SA
SA
NSW
SA
QLD
SA
SA
SA
QLD
QLD
SA
SA
SA
NSW
SA
SA
WA
WA
SA
NSW
SA
WA
QLD
SA
SA
SA
SA
NSW
NSW
NSW
WA
WA
WA
SA
WA
TA
SA
SA
WA
SA
NSW
SA
SA
WA
WA
SA
SA
SA
QLD
WA
WA
WA
NSW
NSW
NSW
SA
VIC
VIC
VIC
VIC
WA
WA
WA
SA
SA
SA
SA
WA
WA
VIC
VIC
SA
SA
SA
NSW
NSW
QLD
QLD
QLD
WA
WA
SA
SA
SA
SA
QLD
SA
SA
SA
SA
WA
WA
WA
WA
WA
SA
QLD
NSW
QLD
SA
QLD
WA
SA
NSW
VIC
VIC
QLD
SA
QLD
WA
SA
SA
WA
NSW
QLD
NSW
QLD
SA
VIC
SA
SA
QLD
QLD
SA
NSW
SA
SA
SA
SA
SA
SA
SA
WA
WA
WA
WA
WA
SA
SA
SA
SA
QLD
QLD
SA
WA
SA
SA
WA
SA
SA
SA
SA
QLD
NSW
NSW
SA
SA
SA
WA
WA
QLD
QLD
QLD
TA
NSW
SA
SA
NSW
WA
WA
WA
SA
SA
QLD
SA
SA
SA
VIC
VIC
QLD
QLD
VIC
SA
SA
SA
SA
SA
TA
WA
WA
WA
SA
QLD
QLD
WA
QLD
QLD
QLD
QLD
SA
SA
QLD
WA
WA
SA
SA
WA
WA
SA
SA
SA
SA
SA
VIC
SA
TA
QLD
QLD
QLD
QLD
WA
WA
SA
WA
WA
WA
SA
WA
QLD
WA
QLD
WA
QLD
WA
WA
QLD
WA
SA
SA
WA
WA
WA
WA
NSW
SA
WA
SA
NSW
NSW
QLD
SA
SA
SA
WA
WA
WA
WA
QLD
QLD
QLD
VIC
SA
QLD
QLD
WA
SA
WA
SA
SA
WA
WA
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
WA
VIC
SA
SA
SA
SA
WA
QLD
QLD
WA
WA
WA
WA
SA
SA
SA
SA
SA
WA
QLD
SA
NSW
NSW
NSW
WA
SA
SA
WA
WA
SA
NSW
QLD
QLD
SA
SA
SA
SA
SA
SA
SA
SA
VIC
WA
WA
SA
QLD
VIC
SA
SA
SA
SA
SA
VIC
WA
SA
QLD
SA
SA
SA
WA
WA
WA
WA
WA
SA
SA
SA
SA
SA
WA
WA
WA
WA
WA
NSW
SA
SA
SA
WA
SA
SA
SA
NSW
NSW
VIC
VIC
QLD
QLD
QLD
SA
SA
WA
WA
VIC
NSW
NSW
NSW
WA
SA
SA
SA
WA
WA
SA
SA
NSW
SA
WA
WA
WA
SA
SA
SA
SA
SA
QLD
QLD
QLD
QLD
WA
WA
SA
SA
NSW
QLD
SA
SA
SA
SA
NSW
NSW
NSW
SA
SA
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
QLD
QLD
QLD
WA
WA
WA
SA
SA
WA
SA
SA
SA
WA
SA
SA
SA
SA
SA
SA
SA
WA
SA
VIC
WA
WA
SA
SA
SA
SA
NSW
WA
SA
WA
WA
WA
QLD
SA
WA
WA
WA
WA
SA
SA
SA
SA
SA
WA
SA
SA
SA
SA
WA
QLD
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
NSW
WA
WA
VIC
WA
WA
WA
WA
SA
NSW
NSW
NSW
SA
SA
WA
WA
SA
NSW
WA
SA
WA
SA
WA
QLD
QLD
WA
WA
QLD
WA
WA
WA
WA
WA
WA
WA
WA
WA
SA
SA
SA
NSW
NSW
WA
WA
SA
SA
WA
WA
WA
SA
SA
SA
NSW
QLD
NSW
WA
WA
WA
QLD
TA
TA
WA
SA
SA
NSW
VIC
VIC
VIC
TA
TA
SA
WA
QLD
SA
SA
QLD
SA
NSW
SA
SA
SA
SA
SA
SA
QLD
NSW
WA
WA
WA
SA
WA
SA
VIC
VIC
QLD
SA
QLD
WA
WA
QLD
QLD
VIC
WA
SA
SA
SA
SA
QLD
WA
WA
WA
SA
VIC
SA
SA
VIC
QLD
QLD
QLD
QLD
QLD
SA
VIC
VIC
QLD
QLD
WA
SA
NSW
QLD
SA
SA
NSW
WA
SA
WA
VIC
NSW
VIC
VIC
VIC
VIC
SA
QLD
WA
WA
WA
NSW
SA
WA
WA
VIC
QLD
QLD
WA
WA
QLD
SA
SA
VIC
WA
WA
WA
WA
QLD
QLD
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
QLD
QLD
QLD
QLD
VIC
SA
SA
SA
WA
QLD
NSW
NSW
SA
SA
SA
NSW
VIC
TA
SA
QLD
NSW
QLD
QLD
QLD
SA
WA
WA
QLD
SA
SA
SA
NSW
WA
WA
WA
SA
SA
SA
WA
WA
SA
WA
WA
SA
WA
WA
WA
WA
WA
SA
SA
SA
QLD
TA
VIC
SA
SA
NSW
SA
SA
SA
SA
NSW
SA
SA
WA
WA
SA
SA
SA
SA
SA
SA
WA
VIC
SA
SA
SA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
WA
WA
TA
TA
QLD
TA
TA
TA
SA
WA
QLD
VIC
VIC
SA
SA
SA
SA
WA
WA
WA
WA
WA
WA
WA
QLD
QLD
QLD
QLD
QLD
QLD
SA
WA
WA
WA
WA
SA
SA
QLD
SA
WA
VIC
SA
SA
SA
SA
SA
QLD
SA
QLD
QLD
SA
SA
WA
SA
SA
SA
SA
TA
TA
VIC
VIC
VIC
VIC
VIC
SA
WA
WA
SA
WA
WA
QLD
QLD
SA
WA
NSW
QLD
WA
WA
WA
WA
WA
SA
VIC
VIC
WA
QLD
WA
WA
WA
WA
WA
NSW
NSW
NSW
WA
SA
SA
NSW
NSW
QLD
SA
SA
WA
SA
SA
SA
SA
SA
NSW
NSW
QLD
NSW
SA
SA
NSW
QLD
QLD
SA
WA
WA
VIC
QLD
QLD
QLD
VIC
SA
SA
SA
QLD
QLD
NSW
SA
WA
QLD
QLD
WA
WA
SA
SA
SA
SA
SA
SA
SA
VIC
VIC
WA
WA
WA
QLD
SA
QLD
SA
SA
SA
SA
SA
WA
SA
SA
WA
WA
SA
SA
SA
SA
NSW
WA
TA
QLD
QLD
QLD
VIC
WA
VIC
SA
WA
VIC
SA
WA
NSW
SA
QLD
SA
SA
WA
WA
SA
SA
WA
WA
WA
WA
WA
WA
WA
SA
WA
WA
WA
WA
VIC
QLD
QLD
VIC
SA
SA
SA
SA
SA
SA
NSW
WA
WA
TA
WA
WA
WA
SA
SA
SA
SA
NSW
WA
WA
WA
WA
SA
WA
WA
WA
WA
WA
WA
WA
NSW
NSW
NSW
VIC
WA
VIC
SA
SA
SA
SA
WA
SA
SA
SA
SA
SA
QLD
QLD
SA
SA
QLD
NSW
NSW
QLD
WA
SA
SA
VIC
WA
VIC
WA
QLD
QLD
QLD
SA
SA
SA
VIC
SA
NSW
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
WA
WA
WA
WA
WA
QLD
QLD
SA
NSW
WA
WA
WA
SA
NSW
NSW
WA
WA
SA
SA
NSW
WA
WA
WA
WA
WA
WA
WA
WA
SA
WA
WA
SA
SA
VIC
SA
SA
VIC
SA
SA
WA
WA
WA
SA
WA
WA
SA
SA
SA
NSW
SA
SA
SA
WA
SA
SA
SA
SA
NSW
VIC
WA
WA
WA
NSW
SA
SA
SA
SA
QLD
QLD
QLD
QLD
QLD
SA
VIC
VIC
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
NSW
WA
WA
SA
WA
VIC
SA
SA
NSW
SA
SA
QLD
SA
QLD
WA
QLD
SA
QLD
WA
WA
WA
SA
SA
NSW
NSW
SA
WA
WA
SA
SA
SA
SA
QLD
SA
QLD
QLD
WA
SA
SA
SA
VIC
SA
VIC
QLD
SA
QLD
SA
SA
SA
WA
WA
WA
SA
SA
WA
SA
SA
SA
SA
WA
WA
WA
SA
WA
WA
QLD
TA
VIC
WA
SA
WA
WA
WA
QLD
SA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
WA
SA
WA
QLD
QLD
SA
SA
WA
WA
WA
WA
SA
SA
SA
SA
QLD
WA
SA
SA
SA
VIC
WA
WA
WA
WA
QLD
SA
WA
SA
SA
QLD
NSW
SA
SA
SA
SA
VIC
SA
QLD
SA
WA
QLD
QLD
QLD
SA
SA
WA
SA
SA
SA
NSW
SA
QLD
SA
SA
SA
QLD
QLD
QLD
QLD
QLD
SA
SA
SA
SA
SA
SA
SA
WA
VIC
WA
NSW
NSW
NSW
NSW
VIC
VIC
VIC
VIC
VIC
VIC
WA
SA
SA
SA
SA
SA
SA
VIC
WA
WA
VIC
WA
WA
WA
SA
WA
NSW
WA
SA
WA
QLD
QLD
QLD
NSW
WA
SA
NSW
NSW
VIC
QLD
NSW
QLD
QLD
VIC
SA
SA
WA
VIC
VIC
WA
WA
WA
QLD
NSW
WA
QLD
SA
WA
SA
SA
WA
VIC
WA
VIC
SA
SA
QLD
SA
SA
VIC
SA
SA
SA
NSW
SA
QLD
SA
SA
QLD
QLD
WA
WA
WA
SA
SA
VIC
VIC
VIC
SA
NSW
SA
SA
SA
SA
VIC
WA
WA
WA
WA
SA
SA
SA
TA
QLD
WA
QLD
SA
NSW
NSW
QLD
QLD
SA
SA
VIC
SA
SA
SA
VIC
QLD
QLD
QLD
QLD
QLD
QLD
WA
SA
NSW
WA
SA
SA
SA
SA
WA
SA
SA
VIC
VIC
WA
VIC
SA
SA
SA
WA
NSW
NSW
SA
WA
WA
NSW
NSW
SA
WA
NSW
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
NSW
WA
QLD
NSW
QLD
QLD
VIC
VIC
VIC
VIC
VIC
WA
TA
TA
WA
WA
SA
SA
TA
QLD
SA
SA
SA
SA
SA
NSW
WA
VIC
QLD
WA
QLD
WA
NSW
QLD
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
QLD
WA
WA
WA
SA
SA
QLD
QLD
QLD
WA
QLD
QLD
SA
SA
SA
QLD
QLD
SA
SA
QLD
SA
SA
SA
SA
SA
VIC
SA
SA
VIC
VIC
SA
SA
WA
WA
NSW
WA
WA
SA
WA
SA
SA
SA
QLD
QLD
TA
VIC
SA
QLD
WA
WA
QLD
QLD
WA
WA
WA
SA
QLD
TA
NSW
QLD
QLD
QLD
QLD
QLD
QLD
QLD
WA
VIC
SA
SA
SA
SA
VIC
NSW
SA
QLD
SA
WA
VIC
VIC
SA
SA
WA
WA
TA
TA
WA
WA
SA
SA
QLD
QLD
QLD
SA
SA
SA
TA
TA
TA
TA
SA
SA
SA
QLD
SA
WA
SA
SA
SA
NSW
NSW
WA
WA
WA
SA
QLD
WA
SA
WA
VIC
SA
TA
SA
QLD
QLD
QLD
QLD
VIC
QLD
NSW
QLD
SA
SA
SA
SA
SA
SA
WA
QLD
QLD
VIC
QLD
QLD
SA
SA
SA
SA
SA
SA
VIC
QLD
WA
WA
SA
SA
SA
SA
SA
SA
WA
WA
VIC
SA
SA
SA
VIC
SA
SA
SA
VIC
VIC
VIC
WA
TA
TA
TA
TA
WA
WA
SA
NSW
NSW
NSW
SA
SA
SA
SA
SA
SA
VIC
VIC
TA
TA
WA
WA
WA
WA
SA
WA
WA
WA
WA
SA
SA
SA
SA
QLD
QLD
QLD
QLD
QLD
QLD
WA
VIC
VIC
WA
VIC
WA
SA
SA
SA
WA
VIC
QLD
WA
NSW
NSW
VIC
VIC
TA
TA
QLD
QLD
WA
SA
SA
SA
SA
QLD
QLD
QLD
QLD
VIC
VIC
SA
SA
WA
WA
SA
QLD
QLD
QLD
SA
QLD
WA
SA
SA
SA
QLD
WA
WA
SA
NSW
NSW
WA
NSW
QLD
QLD
QLD
SA
WA
SA
SA
NSW
SA
SA
NSW
VIC
SA
QLD
SA
SA
SA
SA
QLD
SA
WA
WA
VIC
NSW
WA
WA
SA
VIC
VIC
VIC
VIC
SA
SA
NSW
NSW
WA
WA
WA
WA
QLD
SA
SA
SA
QLD
SA
SA
NSW
NSW
WA
QLD
SA
SA
SA
NSW
VIC
SA
SA
QLD
WA
VIC
TA
TA
TA
WA
SA
SA
VIC
VIC
SA
SA
SA
WA
SA
QLD
QLD
QLD
TA
QLD
QLD
QLD
WA
SA
SA
QLD
SA
SA
QLD
QLD
QLD
QLD
VIC
QLD
QLD
NSW
WA
NSW
VIC
TA
TA
SA
WA
WA
WA
SA
SA
WA
WA
SA
SA
SA
QLD
QLD
WA
WA
VIC
VIC
QLD
WA
WA
WA
WA
QLD
SA
SA
SA
SA
SA
SA
SA
WA
WA
WA
SA
WA
WA
SA
NSW
WA
WA
SA
SA
TA
TA
TA
WA
SA
NSW
NSW
QLD
QLD
QLD
SA
SA
QLD
VIC
WA
VIC
WA
VIC
SA
VIC
NSW
NSW
SA
QLD
SA
TA
TA
NSW
WA
SA
NSW
WA
WA
NSW
WA
NSW
NSW
VIC
VIC
SA
VIC
WA
SA
QLD
QLD
WA
WA
WA
SA
NSW
WA
QLD
SA
VIC
QLD
QLD
QLD
VIC
WA
VIC
SA
WA
QLD
QLD
VIC
WA
WA
WA
WA
WA
WA
WA
NSW
WA
QLD
SA
SA
SA
SA
WA
WA
SA
SA
TA
WA
WA
WA
SA
SA
WA
QLD
QLD
QLD
SA
SA
SA
SA
SA
SA
SA
QLD
QLD
SA
SA
SA
SA
NSW
SA
VIC
SA
NSW
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
VIC
QLD
SA
WA
QLD
SA
VIC
TA
SA
QLD
SA
QLD
SA
SA
VIC
VIC
WA
VIC
WA
VIC
WA
WA
WA
SA
SA
SA
QLD
SA
SA
SA
SA
SA
SA
SA
SA
WA
WA
WA
TA
TA
QLD
QLD
QLD
QLD
WA
SA
SA
SA
SA
SA
SA
SA
SA
WA
NSW
QLD
SA
WA
QLD
QLD
WA
WA
QLD
SA
SA
QLD
WA
WA
WA
WA
WA
SA
WA
VIC
NSW
SA
SA
WA
WA
SA
QLD
QLD
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
SA
NSW
SA
SA
VIC
QLD
SA
SA
WA
WA
NSW
VIC
TA
VIC
VIC
VIC
QLD
WA
WA
QLD
NSW
SA
WA
SA
QLD
VIC
NSW
SA
SA
SA
TA
WA
WA
WA
WA
QLD
WA
WA
WA
WA
WA
TA
WA
WA
SA
WA
WA
WA
SA
SA
SA
WA
QLD
NSW
SA
WA
WA
TA
WA
SA
SA
SA
NSW
QLD
QLD
WA
NSW
NSW
QLD
SA
NSW
NSW
NSW
NSW
NSW
NSW
NSW
NSW
NSW
WA
NSW
VIC
SA
QLD
VIC
SA
WA
VIC
WA
WA
VIC
VIC
VIC
WA
WA
WA
WA
WA
WA
WA
SA
NSW
VIC
TA
WA
VIC
QLD
SA
SA
SA
WA
WA
WA
SA
WA
WA
VIC
SA
SA
SA
NSW
WA
WA
WA
WA
WA
WA
WA
SA
SA
WA
SA
WA
WA
WA
WA
SA
SA
WA
WA
WA
WA
WA
VIC
WA
SA
WA
WA
SA
QLD
SA
SA
SA
SA
QLD
WA
WA
WA
SA
SA
SA
SA
SA
SA
SA
SA
VIC
WA
WA
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
SA
SA
WA
WA
VIC
VIC
WA
WA
WA
WA
WA
SA
SA
SA
SA
VIC
QLD
NSW
SA
WA
WA
WA
WA
WA
VIC
VIC
VIC
QLD
SA
WA
WA
WA
WA
WA
SA
VIC
NSW
WA
SA
WA
QLD
WA
VIC
WA
SA
NSW
SA
QLD
QLD
SA
QLD
QLD
QLD
QLD
QLD
QLD
NSW
SA
SA
SA
SA
NSW
NSW
NSW
SA
WA
WA
QLD
WA
QLD
QLD
SA
SA
TA
TA
TA
QLD
WA
WA
QLD
SA
WA
TA
SA
QLD
QLD
SA
SA
QLD
WA
SA
QLD
WA
SA
SA
SA
NSW
SA
QLD
QLD
SA
SA
SA
QLD
QLD
SA
SA
WA
SA
SA
WA
SA
SA
QLD
QLD
QLD
SA
WA
QLD
WA
SA
SA
QLD
SA
VIC
VIC
SA
WA
SA
TA
TA
SA
SA
WA
SA
SA
SA
SA
SA
VIC
SA
QLD
VIC
SA
SA
SA
SA
SA
SA
SA
SA
VIC
SA
SA
SA
SA
SA
WA
WA
NSW
VIC
SA
WA
SA
SA
QLD
QLD
QLD
SA
SA
SA
WA
WA
WA
WA
SA
SA
SA
NSW
NSW
WA
WA
NSW
SA
QLD
WA
WA
SA
SA
WA
WA
WA
WA
VIC
SA
QLD
QLD
WA
SA
QLD
SA
QLD
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
VIC
WA
WA
WA
WA
SA
SA
NSW
NSW
NSW
NSW
NSW
NSW
NSW
WA
WA
WA
SA
WA
WA
WA
WA
TA
WA
WA
WA
QLD
WA
WA
WA
WA
WA
WA
WA
WA
WA
QLD
WA
WA
SA
SA
SA
SA
SA
WA
NSW
VIC
WA
WA
SA
SA
SA
QLD
SA
WA
QLD
WA
SA
NSW
NSW
WA
SA
TA
VIC
WA
SA
SA
SA
SA
SA
SA
WA
QLD
SA
WA
SA
VIC
WA
VIC
SA
WA
WA
WA
WA
SA
SA
WA
QLD
WA
WA
QLD
VIC
NSW
QLD
QLD
SA
SA
QLD
QLD
SA
QLD
QLD
WA
WA
SA
SA
SA
SA
NSW
WA
WA
WA
WA
SA
SA
NSW
SA
SA
QLD
WA
WA
WA
WA
WA
WA
WA
WA
WA
SA
SA
WA
WA
WA
WA
QLD
VIC
VIC
WA
SA
WA
SA
SA
VIC
VIC
VIC
NSW
NSW
WA
WA
WA
TA
QLD
WA
SA
SA
SA
NSW
SA
VIC
WA
WA
WA
WA
VIC
VIC
NSW
QLD
QLD
SA
WA
WA
SA
SA
QLD
QLD
QLD
VIC
VIC
WA
QLD
NSW
NSW
WA
WA
QLD
VIC
NSW
QLD
QLD
SA
VIC
WA
WA
NSW
WA
WA
WA
NSW
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
SA
WA
SA
SA
SA
VIC
VIC
VIC
SA
WA
SA
SA
SA
SA
SA
WA
QLD
WA
WA
VIC
SA
WA
WA
WA
SA
SA
QLD
WA
WA
NSW
NSW
NSW
SA
SA
QLD
SA
WA
QLD
WA
WA
SA
QLD
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
VIC
SA
QLD
SA
QLD
SA
SA
SA
SA
SA
SA
SA
WA
WA
WA
WA
WA
NSW
WA
NSW
VIC
QLD
SA
VIC
NSW
SA
SA
SA
SA
SA
SA
SA
SA
SA
NSW
SA
WA
WA
WA
SA
QLD
WA
WA
SA
NSW
SA
SA
VIC
SA
SA
WA
SA
SA
SA
VIC
SA
QLD
SA
WA
WA
WA
WA
NSW
SA
WA
SA
SA
VIC
QLD
NSW
WA
WA
WA
WA
WA
WA
WA
WA
WA
WA
SA
SA
SA
SA
SA
WA
WA
NSW
SA
QLD
QLD
QLD
VIC
VIC
WA
WA
SA
NSW
SA
SA
SA
SA
WA
WA
SA
SA
VIC
VIC
WA
WA
VIC
WA
NSW
SA
SA
QLD
WA
WA
WA
WA
WA
WA
SA
WA
WA
NSW
VIC
VIC
SA
SA
SA
SA
SA
WA
WA
WA
WA
QLD
WA
WA
SA
SA
SA
SA
QLD
WA
WA
SA
NSW
QLD
NSW
WA
WA
WA
WA
WA
WA
SA
SA
SA
QLD
VIC
QLD
VIC
SA
SA
QLD
WA
NSW
SA
SA
NSW
NSW
NSW
TA
QLD
WA
SA
SA
SA
SA
WA
WA
SA
SA
SA
WA
QLD
QLD
QLD
QLD
QLD
QLD
QLD
SA
SA
SA
QLD
QLD
SA
QLD
QLD
WA
NSW
NSW
NSW
WA
VIC
WA
VIC
SA
SA
SA
SA
WA
WA
WA
SA
SA
SA
WA
QLD
QLD
SA
SA
WA
SA
SA
SA
SA
WA
SA
WA
WA
SA
WA
SA
WA
WA
WA
WA
QLD
QLD
WA
SA
WA
WA
VIC
NSW
NSW
WA
WA
WA
NSW
SA
WA
WA
WA
SA
NSW
SA
SA
WA
WA
QLD
SA
SA
SA
VIC
QLD
QLD
QLD
QLD
QLD
SA
SA
SA
TA
TA
WA
WA
QLD
QLD
WA
WA
WA
SA
SA
SA
QLD
WA
WA
WA
SA
SA
SA
SA
QLD
QLD
NSW
WA
VIC
SA
SA
WA
SA
WA
SA
SA
SA
VIC
VIC
QLD
QLD
SA
VIC
QLD
QLD
QLD
WA
WA
WA
WA
WA
WA
SA
VIC
WA
SA
WA
WA
SA
WA
SA
NSW
WA

In [9]:
#第三种
iter_columns = zip(df['Causal Part Name'],df['Function Group 4 Digits'],df['Chassis Number'])

for x,y,z in iter_columns:
    print(str(x) +'->' + str(y) +'->' + str(z) )

CYLINDER HEAD, EXCH, SPARE PART->2111->135216
SEALING STRIP, VALVE COVER->2116->135241
EXHAUST MANIFOLD, FRONT AND REAR->2515->135471
INJECTOR SLEEVE, SPARE PART KIT->2119->135521
OIL PAN, PLASTIC->2171->135556
OIL LEVEL SENSOR, OIL LEVEL & TEMP->2846->135556
PRESSURE SENSOR, FUEL/OIL->2846->135576
FAN, ER175 + TR750KSR->2631->136532
PRESSURE SENSOR->2846->136564
OIL HOSE->4319->136564
EXHAUST BRAKE, CLOSED LOOP->2531->136663
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->136703
PRESSURE SENSOR, EXHAUST PRESSURE->2846->136720
BELT TENSIONER, 10K, D=74, L=90, T=37NM->2634->136822
UNIT, C2060->4516->136822
BELT TENSIONER, 10K, D=74, L=90, T=37NM->2634->136880
DIAPHRAGM, DIFF. LOCK->4684->137174
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->137335
EXHAUST BRAKE, CLOSED LOOP->2531->137340
TURBOCHARGER, HX555W-D98K68RAV->2551->137422
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->137481
PRESSURE SENSOR, EXHAUST PRESSURE->2846->200066
SENSOR, NOX 900MM, POST-SCR->2846->200093
SEALING STRIP, OIL PAN PLASTIC->2172->200097
OIL FILTER HOUSING, THERMAL MANAGEMENT->2222->200097
SENSOR, NOX 600 MM->2846->616353
CONTROL UNIT, TRANSMISSION ECU 3000V->4376->640289
BRACKET, FAN BRACKET->2639->652760
CAMSHAFT, TCD 2013 L06 4V->2154->611738
OIL PAN->2171->618804
SENSOR, NOX 600 MM->2846->642919
SENSOR, NOX 600 MM, POST-SCR->2846->650016
CRANKSHAFT->2161->134360
CAMSHAFT AND BEARING KIT, BEARING SHELLS INCLUDED->2154->134751
AIR HOSE, CLUTCH HOUSING->4312->134760
SOLENOID VALVE, CLUTCH OPERATION->4312->134760
CAMSHAFT, VEB6->2154->134790
INJECTOR SLEEVE, SPARE PART KIT->2119->134794
EXHAUST MANIFOLD, FRONT AND REAR->2515->135031
INJECTOR SLEEVE, SPARE PART KIT->2119->135122
EXHAUST VALVE, MULTI GROOVE->2142->135179
SENSOR, NOX 600 MM->2846->135179
EXHAUST VALVE, MULTI GROOVE->2142->135186
EXHAUST VALVE, MULTI GROOVE->2142->135193
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->135196
PRESSURE SENSOR->2846->135236
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->135320
PRESSURE SENSOR, CRANKCASE->2846->135365
PRESSURE SENSOR, FUEL/OIL->2846->135365
EXHAUST BRAKE, CLOSED LOOP->2531->135387
PRESSURE SENSOR, EXHAUST PRESSURE->2846->135427
LIP SEAL->4658->135460
COMPANION FLANGE, ASSY, OUTPUT SHAFT->4659->135460
EXHAUST MANIFOLD, FRONT AND REAR->2515->135516
AIR VALVE, EPG /  WASTEGATE- GEN 3->2539->135520
PIPE SET, WG TURBO->2539->135520
TEMPERATURE SENSOR, DARTS PIGTAIL, A CODED->2846->135520
ACTUATOR SERVICE KIT, FOR SPARE PART USE->2539->135525
SOLENOID VALVE, CLUTCH OPERATION->4312->135525
SOLENOID VALVE, CLUTCH OPERATION->4312->135556
GASKET, MULTI-DISC BRAKE->4319->135556
SEALING RING, 57,5*90*12   INPUT SHAFT->4319->135556
TIMING GEAR PLATE, UTURBOC-GRINDED->2126->135632
OIL FILTER HOUSING, THERMAL MANAGEMENT->2222->135632
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->135632
CRANKSHAFT SEAL, ASSY FRONT->2167->135633
CHARGE AIR COOLER, WIDE->2651->135633
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->135684
SEALING STRIP, VALVE COVER->2116->135698
OIL HOSE->4319->135698
OIL HOSE, GEARBOX->4319->135800
CYLINDER LINER KIT, MONOTHERM->2131->135817
SENSOR, NOX 600 MM->2846->135847
OIL HOSE, GEARBOX->4319->135875
GASKET, TIMING GEAR COVER->2152->135885
OIL FILTER HOUSING, HDE13 TM ASSY->2222->135885
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->135885
CHARGE AIR HOSE, HOT SIDE->2652->135885
DIAPHRAGM, DIFF. LOCK->4684->135885
GASKET, OIL FILTER HOUSING->4911->135889
PRESSURE SENSOR, CRANKCASE PRESSURE->2846->135903
PRESSURE SENSOR, FUEL/OIL->2846->135903
TEMPERATURE SENSOR, COOLANT/OIL TEMP->2846->135903
PRESSURE SENSOR, BOOST PRESSURE / TEMP->2846->135919
SPEED SENSOR, CAMSHAFT/CRANKSHAFT->2846->135919
PRESSURE SENSOR->2846->135938
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->135938
OIL HOSE->4319->135938
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->135952
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->135981
SENSOR, NOX 600 MM, POST-SCR->2846->135981
RADIATOR, WIDE->2611->136037
RADIATOR, TCMAOH2->4911->136037
RADIATOR, TCMAOH2->4911->136039
PRESSURE SENSOR, BOOST PRESSURE / TEMP->2846->136049
OIL FILTER HOUSING, THERMAL MANAGEMENT->2222->136059
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->136059
PRESSURE SENSOR, EXHAUST PRESSURE->2846->136069
PRESSURE SENSOR, FUEL/OIL->2846->136069
PRESSURE SENSOR, FUEL/OIL->2846->136069
CONTROL VALVE, BY PASS OIL COOLER->2229->136084
OIL FILTER HOUSING, HDE13 TM ASSY->2222->136095
DIAPHRAGM, DIFF. LOCK->4684->136095
PRESSURE SENSOR, FUEL/OIL->2846->136110
PISTON, MULTI-DISC BRAKE, ASSY->4319->136140
EXHAUST MANIFOLD, FRONT AND REAR->2515->136259
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->136305
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->136306
FLYWHEEL HOUSING, ASSY->2125->136345
GASKET, TURBOCHARGER->2552->136345
PRESSURE SENSOR, CRANKCASE PRESSURE->2846->136396
PRESSURE SENSOR, CRANKCASE PRESSURE->2846->136396
VALVE SEAL->2149->136397
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->136397
TURBOCHARGER, HX555W-D98K68RAV->2551->136403
ROCKER ARM, INLET->2145->136414
GASKET, TIMING GEAR COVER->2152->136414
OIL FILTER HOUSING, THERMAL MANAGEMENT->2222->136414
BELT TENSIONER, 10K, D=74, L=90, T=37NM->2634->136414
IDLER PULLEY, 10K, DOB 74->2634->136414
PRESSURE SENSOR, CRANKCASE PRESSURE->2846->136430
CONTROL VALVE, PISTON COOLING JET 24V->2229->136436
CONTROL VALVE, THERMOSTAT 24V->2229->136436
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->136436
CONTROL UNIT, EMS 2.2 MIN "I", COMPLETE->2841->136460
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->136519
IDLER PULLEY, 10K, DOB 74->2634->136529
INLET VALVE, MULTI GROOVE->2141->136533
ACTUATOR SERVICE KIT, FOR SPARE PART USE->2539->136537
IDLER PULLEY, 10K, DOB 74->2634->136537
PRESSURE SENSOR->2846->136539
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->136542
EXHAUST MANIFOLD, ASSEMBLY->2510->136558
EXHAUST MANIFOLD, ASSEMBLY->2510->136560
PRESSURE SENSOR, FUEL/OIL->2846->136569
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->136603
OIL HOSE, GEARBOX->4319->136613
ACTUATOR SERVICE KIT, FOR SPARE PART USE->2539->136630
ACTUATOR SERVICE KIT, FOR SPARE PART USE->2539->136661
OIL HOSE, GEARBOX->4319->136661
OIL HOSE, GEARBOX->4319->136667
OIL HOSE, GEARBOX->4319->136678
OIL HOSE->4319->136683
CRANKSHAFT SEAL, (REAR)->2167->136705
GASKET, MULTI-DISC BRAKE->4319->136705
OIL HOSE, GEARBOX->4319->136705
OIL HOSE, GEARBOX->4319->136705
SEALING RING, 57,5*90*12   INPUT SHAFT->4319->136705
TEMPERATURE SENSOR, DARTS PIGTAIL, A CODED->2846->136710
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->136731
EXHAUST MANIFOLD, FRONT AND REAR->2515->136779
EXHAUST VALVE, MULTI GROOVE->2142->136788
CHARGE AIR HOSE, HOT SIDE->2652->136788
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->136788
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->136788
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->136788
SEALING STRIP, VALVE COVER->2116->136805
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->136805
EXHAUST BRAKE, CLOSED LOOP->2531->136805
TURBOCHARGER, HX555W-D98K68RAV->2551->136805
RADIATOR, TCMAOH2->4911->136805
EXHAUST MANIFOLD, ASSEMBLY->2510->136811
EXHAUST VALVE, MULTI GROOVE->2142->136812
UNIT INJECTOR->2374->136812
EXHAUST VALVE, MULTI GROOVE->2142->136815
AIR VALVE, EPG /  WASTEGATE- GEN 3->2539->136820
PIPE SET, AVU TO BUTTERFLY->2539->136820
PRESSURE SENSOR, EXHAUST PRESSURE->2846->136822
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->136840
TEMPERATURE SENSOR, DARTS PIGTAIL, A CODED->2846->136840
EXHAUST VALVE, MULTI GROOVE->2142->136849
ACTUATOR SERVICE KIT, FOR SPARE PART USE->2539->136849
GASKET, TURBOCHARGER->2552->136849
EXHAUST BRAKE, CLOSED LOOP->2531->136874
RADIATOR, TCMAOH2->4911->136898
STUD, M10*58*43->2550->136904
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->136928
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->136935
CAMSHAFT, VEB6->2154->137007
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->137056
IDLER PULLEY, 10K, DOB 74->2634->137091
EXHAUST MANIFOLD, ASSEMBLY->2510->137105
EXHAUST MANIFOLD, FRONT AND REAR->2515->137114
TURBOCHARGER, HX555W-D98K68RAV->2551->137114
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->137120
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->137141
EXHAUST BRAKE, CLOSED LOOP->2531->137141
AIR VALVE, EPG /  WASTEGATE- GEN 3->2539->137141
POSITION SENSOR, POSITION SENSOR->4326->137148
EXHAUST MANIFOLD, FRONT AND REAR->2515->137165
TURBOCHARGER, HX555W-D98K68RAV->2551->137183
PRESSURE SENSOR->2846->137199
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->137214
TURBOCHARGER, HX555W-D98K68RAV->2551->137214
EXHAUST VALVE, MULTI GROOVE->2142->137247
OIL HOSE->4319->137247
EXHAUST MANIFOLD, ASSEMBLY->2510->137248
IDLER PULLEY, 10K, DOB 74->2634->137251
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->137267
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->137270
SEALING STRIP, VALVE COVER->2116->137278
TURBOCHARGER, HX555W-D98K68RAV->2551->137313
OIL HOSE, GEARBOX->4319->137315
CONNECTION PIPE, COOLANT BY-PASS->2629->137324
TURBOCHARGER, HX555W-D98K68RAV->2551->137335
TURBOCHARGER, HX555W-D98K68RAV->2551->137336
EXHAUST VALVE, MULTI GROOVE->2142->137347
CYLINDER HEAD, SPARE PART->2111->137349
ROCKER ARM, INLET->2145->137349
TIMING GEAR PLATE, SPARE PART->2154->137398
AIR VALVE, EPG /  WASTEGATE- GEN 3->2539->137398
TURBOCHARGER, EXCH, HX555W-D98K68RAV->2551->137398
TURBOCHARGER, HX555W-D98K68RAV->2551->137398
REPAIR KIT, WASTEGATE->2552->137398
OIL HOSE->4319->137398
EXHAUST VALVE, MULTI GROOVE->2142->137400
EXHAUST MANIFOLD, ASSEMBLY->2510->137413
TURBOCHARGER, EXCH, HX555W-D98K68RAV->2551->137413
CHARGE AIR HOSE, HOT SIDE->2652->137413
TEMPERATURE SENSOR, DARTS PIGTAIL, A CODED->2846->137413
GASKET, OIL FILTER HOUSING->2228->137419
PRESSURE SENSOR, EXHAUST PRESSURE->2846->137441
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->137462
EXHAUST BRAKE, CLOSED LOOP->2531->137462
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->137462
TURBOCHARGER, HX555W-D98K68RAV->2551->137495
PUMP UNIT, WITH CLUTCH MD13 URET->2621->136109
COVER, FILTER PROTECTION->4319->136109
EXHAUST BRAKE, CLOSED LOOP->2531->135665
CONTROL VALVE, 24V->2533->135665
PUMP UNIT, COOLANT PUMP->2621->135665
PRESSURE SENSOR, EXHAUST PRESSURE->2846->135665
PRESSURE SENSOR, CRANKCASE PRESSURE->2846->200000
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->200000
CONNECTOR, COOL-F16,00-MP12*180->2616->200024
CONTROL UNIT, TRANSMISSION->4326->200024
INLET VALVE, MULTI GROOVE->2141->200037
FLANGE NUT, M10*9,5->2379->200037
EXHAUST MANIFOLD, FRONT AND REAR->2515->200041
DIAPHRAGM, DIFF. LOCK->4684->200045
FAN, S842B + HD11-750->2631->200049
BELT TENSIONER, 10K, D=74, L=90, T=37NM->2634->200049
EXHAUST VALVE, MULTI GROOVE->2142->200056
PRESSURE SENSOR, CRANKCASE PRESSURE->2846->200056
CONTROL UNIT, EMS 2.2 MIN I TEA2+->2841->200057
SENSOR, NOX 600 MM, POST-SCR->2846->200065
COVER, COOLANT DUCT (UEGR)->2129->200066
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->200066
TURBOCHARGER, HX555W-D98K68RAV->2551->200066
GEAR SELECTOR, ELECTRIC GEAR-SHIFT, RHD->4323->200077
GEAR SELECTOR, ELECTRIC GEAR-SHIFT, RHD->4323->200077
GASKET, OIL FILTER HOUSING->2228->200093
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->200093
TURBOCHARGER, HX555W-D98K68RAV->2551->200093
SEALING RING->2559->200093
OIL FILTER HOUSING, HDE13 TM ASSY->2222->200096
TURBOCHARGER, HX555W-D98K68RAV->2551->200096
SENSOR, NOX 600 MM, POST-SCR->2846->200116
SEALING RING, OUTPUT SHAFT->4658->200116
PRESSURE SENSOR, EXHAUST PRESSURE->2846->200145
IDLER PULLEY, 10K, DOB 74->2634->200158
CONTROL VALVE, 24V->2533->200224
AIR VALVE, EPG /  WASTEGATE- GEN 3->2539->200258
ROLLER BEARING, TAPERED->4313->133051
TIMING GEAR PLATE->2126->134040
FLYWHEEL, TWIN MASS FLYWHEEL->2166->134040
SEALING RING, 57,5*90*12   INPUT SHAFT->4319->134040
TEMPERATURE SENSOR, DARTS PIGTAIL, A CODED->2846->134507
AIR VALVE, EPG /  WASTEGATE- GEN 3->2539->135409
CHARGE AIR HOSE, HOT SIDE->2652->135409
PRESSURE SENSOR, BOOST PRESSURE / TEMP->2846->135409
TEMPERATURE SENSOR, DARTS PIGTAIL, A CODED->2846->135409
BELT TENSIONER, 10K- D=74- L=95- T=32N.M->2634->135415
BELT TENSIONER, 10PK, DOB=79.5, L=95->2634->135415
PRESSURE SENSOR->2846->135648
EXHAUST MANIFOLD, FRONT, REAR->2511->135690
SEALING STRIP, VALVE COVER->2116->135881
RADIATOR, TCMAOH2->4911->135936
TIMING GEAR PLATE->2126->136032
IDLER GEAR, LOWER->2153->136032
TEMPERATURE SENSOR, DARTS PIGTAIL, A CODED->2846->136032
GROMMET, PASS-THRU 34MM->2849->136032
GASKET, OIL FILTER HOUSING->2228->136093
OIL LEVEL SENSOR, OIL LEVEL & TEMP->2846->136093
SPEED SENSOR, CAMSHAFT/CRANKSHAFT->2846->136100
TIMING GEAR PLATE->2126->136143
DIAPHRAGM, DIFF. LOCK->4684->136143
FLYWHEEL, TWIN MASS FLYWHEEL->2166->136170
TIMING GEAR PLATE->2126->136175
FLYWHEEL, TWIN-MASS->2160->136175
RADIATOR, TCMAOH2->4911->136185
INJECTOR SLEEVE, SPARE PART KIT->2119->136231
FLYWHEEL HOUSING, ASSY->2125->136307
IDLER GEAR, SERVO PUMP->2153->136307
GASKET, MULTI-DISC BRAKE->4319->136307
SEALING RING, 57,5*90*12   INPUT SHAFT->4319->136307
LIP SEAL->4658->136365
CONTROL VALVE, 24V->2533->136426
TIMING GEAR PLATE->2126->136469
TIMING GEAR COVER, WITH OIL TRAP->2151->136469
CRANKSHAFT SEAL, (REAR)->2167->136469
PIPE, ASSY DIPSTICK->2215->136469
EXHAUST MANIFOLD, ASSEMBLY->2510->136584
OIL HOSE, GEARBOX->4319->136653
OIL HOSE, GEARBOX->4319->136653
EXHAUST BRAKE, CLOSED LOOP->2539->136762
SENSOR, NOX 900MM, POST-SCR->2846->136868
TEMPERATURE SENSOR, DARTS PIGTAIL, A CODED->2846->136868
INJECTOR SLEEVE, SPARE PART KIT->2119->136950
BELT TENSIONER, 10K, D=86.5, L=90, T=34N->2634->136973
SEALING STRIP, TIMING GEAR COVER->2152->137011
FLYWHEEL, TWIN MASS FLYWHEEL->2166->137011
CRANKSHAFT SEAL, (REAR)->2167->137011
PRESSURE SENSOR, EXHAUST PRESSURE->2846->137011
BELT TENSIONER, 10PK, DOB=79.5, L=95->2634->137090
IDLER PULLEY->2634->137090
OIL HOSE, GEARBOX->4319->137090
OIL HOSE, GEARBOX->4319->137090
RADIATOR, TCMAOH2->4911->137090
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->137175
GASKET, CYLINDER HEAD->2112->137182
VALVE COVER, WITH OIL TRAP->2115->137182
EXHAUST BRAKE, CLOSED LOOP->2539->137182
PRESSURE SENSOR, EXHAUST PRESSURE->2846->137182
SOLENOID VALVE, CLUTCH OPERATION->4134->137182
OIL HOSE, GEARBOX->4319->137182
OIL FILLER CAP->2215->137229
PRESSURE SENSOR->2846->137301
SOLENOID VALVE, CLUTCH OPERATION->4134->137309
SEALING STRIP, VALVE COVER->2116->137314
FLYWHEEL, TWIN-MASS->2160->137314
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->137314
CYLINDER, ASSY, CLUTCH->4134->137330
SOLENOID VALVE, CLUTCH OPERATION->4134->137330
FLYWHEEL, TWIN MASS FLYWHEEL->2166->137345
DIAPHRAGM, DIFF. LOCK->4684->137345
FAN HUB, MD13/16->2631->137362
EXHAUST BRAKE, CLOSED LOOP->2539->137364
DIAPHRAGM, DIFF. LOCK->4684->137373
CONTROL VALVE, 24V->2533->137395
GEAR SHIFT LEVER CARRIER, ASSY, RHD, VAL-CHD->4323->137417
BELT TENSIONER, 10K, D=86.5, L=90, T=34N->2634->137464
CYLINDER, ASSY, CLUTCH->4134->137464
SOLENOID VALVE, CLUTCH OPERATION->4134->137464
SOLENOID VALVE, CLUTCH OPERATION->4134->137464
FLYWHEEL, TWIN MASS FLYWHEEL->2166->137522
FLYWHEEL, TWIN MASS FLYWHEEL->2166->137522
SEALING STRIP, TIMING GEAR COVER->2152->137529
PRESSURE SENSOR->2846->137102
BELT TENSIONER, 10K, D=86.5, L=90, T=34N->2634->137167
BELT TENSIONER, 10PK, DOB=79.5, L=95->2634->137167
TEMPERATURE SENSOR, DARTS PIGTAIL, A CODED->2846->137167
DIAPHRAGM, DIFF. LOCK->4684->137167
OIL HOSE, GEARBOX->4319->137376
OIL HOSE, GEARBOX->4319->137376
SUPPORT BEARING, ASSY C2055/C2060/C2065->4519->137376
BELT TENSIONER, 10PK, DOB=79.5, L=95->2634->137423
TIMING GEAR PLATE->2126->200010
IDLER GEAR, LOWER->2153->200010
HOSE, UPPER RADIATOR->2615->200030
TURBOCHARGER, (A/WG)->2551->200215
FAN, ER130 + TR680KSR->2631->134193
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->134193
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->134193
OIL PAN, ASSY->2171->134648
CONTROL VALVE, THERMOSTAT 24V->2229->135484
SLEEVE, INJECTOR->2119->134565
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->134661
PRESSURE SENSOR, FUEL/OIL->2846->135067
OIL LEVEL SENSOR, OIL LEVEL & TEMP->2846->135339
OIL LEVEL SENSOR, OIL LEVEL & TEMP->2846->136226
PRESSURE SENSOR, FUEL/OIL->2846->136226
OIL PAN, ASSY->2171->134444
PRESSURE SENSOR, FUEL/OIL->2846->134444
SENSOR, NOX 600 MM->2846->134455
OIL FILTER HOUSING, ASSY->2222->135353
PRESSURE SENSOR, FUEL/OIL->2846->135408
INJECTOR SLEEVE, SPARE PART KIT->2119->135513
INLET MANIFOLD, WITH SEAL->2511->135644
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->135651
SOLENOID VALVE, CLUTCH OPERATION->4312->135664
SEALING STRIP, VALVE COVER->2115->136016
SENSOR, NOX 600 MM->2846->136016
CONTROL VALVE, BY PASS OIL COOLER->2229->136051
OIL FILTER HOUSING, ASSY->2222->136087
EXHAUST MANIFOLD, FRONT->2515->136087
BRACKET, CHARGE AIR PIPE->2652->136087
SEALING RING, D-SHAPE->2211->136096
EXHAUST MANIFOLD, MIDDLE->2515->136119
OIL LEVEL SENSOR, OIL LEVEL & TEMP->2846->136119
SEALING RING, D-SHAPE->2211->136161
PRESSURE SENSOR, FUEL/OIL->2846->136261
EXHAUST MANIFOLD, FRONT->2515->136265
CONTROL VALVE, BY PASS OIL COOLER->2229->136269
EXHAUST MANIFOLD, FRONT->2515->136269
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->136269
OIL HOSE, GEARBOX->4319->136299
EXHAUST MANIFOLD, FRONT->2515->136301
CONTROL VALVE, PISTON COOLING JET 24V->2229->136324
PRESSURE SENSOR, FUEL/OIL->2846->136324
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->136789
TURBOCHARGER, HX52W-D98K66RAV/ VOLVO->2551->136829
PUMP UNIT, COOLANT PUMP WITH CLUTCH->2621->136829
FILLER PIPE, MD11/FM->2616->136831
COOLANT PIPE, LOWER->2615->136896
CONTROL VALVE, THERMOSTAT 24V->2229->136920
EXHAUST PRESSURE GOVERNOR, MARACCAS->2538->136920
PUMP UNIT, COOLANT PUMP WITH CLUTCH->2621->136920
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->136920
SENSOR, NOX 600 MM, POST-SCR->2846->136920
INSPECTION COVER->4312->136920
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->136940
EXHAUST MANIFOLD, FRONT->2515->136992
PUMP UNIT, COOLANT PUMP WITH CLUTCH->2621->136992
OIL HOSE, GEARBOX->4319->137100
SENSOR, NOX 600 MM, POST-SCR->2846->137154
OIL HOSE->4319->137154
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->137252
SENSOR, NOX 600 MM, POST-SCR->2846->137319
OIL PAN, ASSY->2171->137375
EXHAUST MANIFOLD, MIDDLE->2515->137375
TURBOCHARGER, HX52W-D98K66RAV/ VOLVO->2551->137375
EXHAUST MANIFOLD, MIDDLE->2515->137377
AIR VALVE, EPG /  WASTEGATE- GEN 3->2539->137415
OIL HOSE, GEARBOX->4319->137415
OIL HOSE->4319->137474
CRANKSHAFT SEAL, ASSY FRONT->2167->137479
SEALING STRIP, OIL PAN->2172->137479
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->137479
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->137479
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->137479
OIL PAN, ASSY->2171->137880
THERMOSTAT FAN, EXCH, ER130 + TR680KSR->2631->137880
OIL HOSE->4319->137897
OIL HOSE->4319->137926
SENSOR, NOX 600 MM, POST-SCR->2846->733987
GASKET, TIMING GEAR COVER->2152->134452
CRANKSHAFT SEAL, ASSY FRONT->2167->134452
CONTROL VALVE, THERMOSTAT 24V->2229->135068
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->135068
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->135335
PRESSURE SENSOR, FUEL/OIL->2846->135429
CONTROL UNIT, EMS 2.2 MIN I TEA2+->2841->135478
PRESSURE SENSOR, CRANKCASE PRESSURE->2846->136013
OIL LEVEL SENSOR, OIL LEVEL & TEMP->2846->136062
PRESSURE SENSOR, FUEL/OIL->2846->136181
PRESSURE SENSOR, FUEL/OIL->2846->136181
PRESSURE SENSOR, FUEL/OIL->2846->136251
PRESSURE SENSOR, FUEL/OIL->2846->136251
FAN, ER130 + TR680KSR->2631->137584
PRESSURE SENSOR, FUEL/OIL->2846->134848
SENSOR, NOX 900MM, POST-SCR->2846->135233
GEAR, 2:ND MAIN SHAFT->4314->135336
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->135356
PRESSURE SENSOR, FUEL/OIL->2846->135356
OIL HOSE->4319->135733
PRESSURE SENSOR, FUEL/OIL->2846->136075
BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634->136604
PRESSURE CAP, (75KPA)->2613->137002
COOLANT PUMP, HT PUMP UNIT->2621->137002
CYLINDER, ASSY, CLUTCH->4134->137002
FAN, 842B + XD11-680->2631->137610
FAN, 842B + XD11-680->2631->138016
SENSOR, NOX 600 MM->2846->134673
INJECTOR SLEEVE, SPARE PART KIT->2119->134805
OIL FILTER HOUSING, THERMAL MANAGEMENT->2222->135054
PRESSURE SENSOR, FUEL / OIL PRESSURE->2846->135130
EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->135207
OIL LEVEL SENSOR, OIL LEVEL & TEMP->2846->135211
PRESSURE SENSOR, EXHAUST PRESSURE->2846->135211

In [10]:
#更好阅读的方式
new_col = []

iter_columns = zip(df['Causal Part Name'],df['Function Group 4 Digits'],df['Chassis Number'])
for x,y,z in iter_columns:
    new_col.append(str(x) +'->' + str(y) +'->' + str(z))
    
df['new_col'] = new_col
df['new_col'][:20]

0         CYLINDER HEAD, EXCH, SPARE PART->2111->135216
1              SEALING STRIP, VALVE COVER->2116->135241
2        EXHAUST MANIFOLD, FRONT AND REAR->2515->135471
3         INJECTOR SLEEVE, SPARE PART KIT->2119->135521
4                        OIL PAN, PLASTIC->2171->135556
5      OIL LEVEL SENSOR, OIL LEVEL & TEMP->2846->135556
6               PRESSURE SENSOR, FUEL/OIL->2846->135576
7                   FAN, ER175 + TR750KSR->2631->136532
8                         PRESSURE SENSOR->2846->136564
9                                OIL HOSE->4319->136564
10             EXHAUST BRAKE, CLOSED LOOP->2531->136663
11    EXHAUST MANIFOLD, WITH TURBO FLANGE->2511->136703
12      PRESSURE SENSOR, EXHAUST PRESSURE->2846->136720
13    BELT TENSIONER, 10K, D=74, L=90, T=37NM->2634-...
14                            UNIT, C2060->4516->136822
15    BELT TENSIONER, 10K, D=74, L=90, T=37NM->2634-...
16                  DIAPHRAGM, DIFF. LOCK->4684->137174
17    BELT TENSIONER, 10K- D=74- L=95- T=43N.M->2634...
18             EXHAUST BRAKE, CLOSED LOOP->2531->137340
19         TURBOCHARGER, HX555W-D98K68RAV->2551->137422
Name: new_col, dtype: object

In [11]:
#7.1 map
#算出+GST以后的total payment
def calculate_something(x):
    return float(x)*1.1
df['Total_plus_tax'] = df['Total_Payment'].map(calculate_something)
df[['Total_Payment','Total_plus_tax']][:20]

    Total_Payment  Total_plus_tax
0         7370.01        8107.011
1          173.22         190.542
2          509.62         560.582
3         1864.20        2050.620
4         2246.32        2470.952
5          109.80         120.780
6          314.84         346.324
7         1736.57        1910.227
8          320.79         352.869
9          347.44         382.184
10        1723.74        1896.114
11         771.03         848.133
12         406.62         447.282
13         627.77         690.547
14         460.66         506.726
15         503.11         553.421
16         141.50         155.650
17         324.84         357.324
18        1798.98        1978.878
19        2926.90        3219.590

In [12]:
#用lambda改写
df['Total_plus_tax'] = df['Total_Payment'].map(lambda cell: cell*1.1)
df[['Total_Payment','Total_plus_tax']][:20]

    Total_Payment  Total_plus_tax
0         7370.01        8107.011
1          173.22         190.542
2          509.62         560.582
3         1864.20        2050.620
4         2246.32        2470.952
5          109.80         120.780
6          314.84         346.324
7         1736.57        1910.227
8          320.79         352.869
9          347.44         382.184
10        1723.74        1896.114
11         771.03         848.133
12         406.62         447.282
13         627.77         690.547
14         460.66         506.726
15         503.11         553.421
16         141.50         155.650
17         324.84         357.324
18        1798.98        1978.878
19        2926.90        3219.590

In [13]:
#将Causal Part Name第一部分拿出来
df['Causal Part first'] = df['Causal Part Name'].map(lambda x: str(x).lower().split(',')[0])
df['Causal Part first'][:10]

0       cylinder head
1       sealing strip
2    exhaust manifold
3     injector sleeve
4             oil pan
5    oil level sensor
6     pressure sensor
7                 fan
8     pressure sensor
9            oil hose
Name: Causal Part first, dtype: object

In [14]:
#7.2 apply

In [15]:
#QLD','NSW','VIC'是1.1倍，其他的1.2倍
df['Total_Payment_plus_tax'] = df.apply(lambda row: row['Total_Payment']*1.2 if row['State'] not in ['QLD', 'NSW','VIC']
                                       else row['Total_Payment']*1.1, axis = 1)
df['Total_Payment_plus_tax']

0        8107.011
1         190.542
2         560.582
3        2237.040
4        2695.584
           ...
24374     408.480
24375     612.960
24376     410.280
24377     408.480
24378    1432.620
Name: Total_Payment_plus_tax, Length: 24379, dtype: float64

In [16]:
#根据上面的写函数, 
def paytax(row):
    if row['State'] not in ['QLD','NSW','VIC']:
        ans = row['Total_Payment']*1.2
    else:
        ans = row['Total_Payment']*1.1    
    return ans

df['Total_Payment_plus_tax'] = df.apply(paytax,axis=1)
df['Total_Payment_plus_tax']

0        8107.011
1         190.542
2         560.582
3        2237.040
4        2695.584
           ...
24374     408.480
24375     612.960
24376     410.280
24377     408.480
24378    1432.620
Name: Total_Payment_plus_tax, Length: 24379, dtype: float64

In [17]:
#8. str的处理
test_str='BELT TENSIONER, 10k, D=74, L=90, T=37NM'
test_str=test_str.replace(',','->').replace('=','=>').split('->')
test_str

['BELT TENSIONER', ' 10k', ' D=>74', ' L=>90', ' T=>37NM']

In [18]:
#9.bin
bin_mileage = [0,20000,50000,10000000000000]
bin_name = ['low','Medium','Aged']
cats = pd.cut(df['Vehicle Mileage On Claim (km)'],bin_mileage,labels = bin_name)
cats
df['Type'] = cats
df[['Vehicle Mileage On Claim (km)','Type']]

       Vehicle Mileage On Claim (km)  Type
0                             653344  Aged
1                             341427  Aged
2                             490752  Aged
3                             501090  Aged
4                             701166  Aged
...                              ...   ...
24374                         166669  Aged
24375                         116771  Aged
24376                         127924  Aged
24377                         115530  Aged
24378                         261028  Aged

[24379 rows x 2 columns]

In [19]:
#10.combine

In [20]:
df_names = pd.DataFrame(data=[[1,'Jason'],[2,'Mike']],columns=['ID','Name'])
df_names
df_department = pd.DataFrame(data=[[1,'IT'],[2,'Purchase']],columns=['ID','Department'])
df_department

   ID Department
0   1         IT
1   2   Purchase

In [21]:
df = pd.merge(left=df_names, right=df_department, on=['ID'], how='left')
df

   ID   Name Department
0   1  Jason         IT
1   2   Mike   Purchase

In [22]:
#如果join on的名字不一样
df_names = pd.DataFrame(data=[[1,'Jason'],[2,'Mike']],columns=['ID','Name'])
df_names
df_department = pd.DataFrame(data=[[1,'IT'],[2,'Purchase']],columns=['Identifier','Department'])
df_department
df = pd.merge(left=df_names, right=df_department, left_on=['ID'],right_on=['Identifier'], how='left')
df

   ID   Name  Identifier Department
0   1  Jason           1         IT
1   2   Mike           2   Purchase

In [23]:
#11.Concat
df1 = pd.read_csv(r'datasets/concat/Tempature.csv')
df2 = pd.read_csv(r'datasets/concat/Velocity.csv')

df1['Type'] = 'Tempature'
df2['Type'] = 'Velocity'

df = pd.concat([df1,df2], ignore_index = True)
df

                Time_Stamp     Value       Type
0      2019-06-19 08:00:17  18.16999  Tempature
1      2019-06-19 08:00:26  17.55999  Tempature
2      2019-06-19 08:01:11  15.91000  Tempature
3      2019-06-19 08:01:28  16.36000  Tempature
4      2019-06-19 08:02:25  16.36000  Tempature
...                    ...       ...        ...
25910  2019-06-27 21:19:18   0.18000   Velocity
25911  2019-06-27 21:20:04   0.16000   Velocity
25912  2019-06-27 21:30:59   0.16000   Velocity
25913  2019-06-27 21:31:36   0.20000   Velocity
25914  2019-06-27 21:35:31   0.20000   Velocity

[25915 rows x 3 columns]

In [24]:
#12.Groupby
df = pd.read_csv(r'datasets/3.4 Wty_Claims_data_new.csv')
grp = df.groupby(['State','Repairing Dealer'])['Vehicle Mileage On Claim (km)'].mean()
type(grp)

pandas.core.series.Series

In [25]:
df_grped = pd.DataFrame(grp)
df_grped.reset_index(drop=False,inplace=True)
df_grped

   State  Repairing Dealer  Vehicle Mileage On Claim (km)
0    NSW            6000.0                  259371.976744
1    NSW            7830.0                  955105.000000
2    NSW           89508.0                  380593.894737
3    NSW           93385.0                  391717.898406
4    NSW          235191.0                  356586.838710
5    NSW          480274.0                  372007.847222
6    NSW          501207.0                  297411.655172
7    NSW          511728.0                  346510.677966
8    NSW          584693.0                  208510.166667
9    NSW          629287.0                  201403.172566
10   NSW          630208.0                  335178.205882
11   NSW          688845.0                  150839.250000
12   NSW          698302.0                  417827.000000
13   NSW          762478.0                  370307.683673
14   NSW          766085.0                  421009.916143
15   NSW          788051.0                  318881.737864
16   QLD           85993.0                  391024.361607
17   QLD           89540.0                  341847.531532
18   QLD           93351.0                  335866.394429
19   QLD          406291.0                  219375.809524
20   QLD          488428.0                  408165.493548
21   QLD          490233.0                  403913.875000
22   QLD          542468.0                  338630.333333
23   QLD          543517.0                  644975.375000
24   QLD          630207.0                  359523.734940
25   QLD          754615.0                   10358.000000
26    SA           52589.0                  425529.728972
27    SA           92197.0                  385519.247372
28    SA          600828.0                  336665.492830
29    SA          601571.0                  291910.485222
30    SA          691188.0                  383622.946934
31    SA          756048.0                  167744.666667
32    TA          480277.0                  330696.169231
33    TA          601570.0                  276822.662651
34    TA          631891.0                  247014.073529
35   VIC           19053.0                  286386.529412
36   VIC           79129.0                  299036.382550
37   VIC          396485.0                  327629.242424
38   VIC          429723.0                  215961.615385
39   VIC          482666.0                  405532.640000
40   VIC          552993.0                  323237.320158
41   VIC          704541.0                  213453.000000
42   VIC          880625.0                  359426.752044
43    WA           70287.0                  389137.345250
44    WA           92767.0                  366155.711012
45    WA          542457.0                  375488.112310
46    WA          601578.0                  280269.721939
47    WA          629286.0                  238600.518519
48    WA          630205.0                  270134.513158
49    WA          742348.0                  120008.000000

In [26]:
#把上面结合成一句
df_change = pd.DataFrame(df.groupby(['Repairing Dealer','State'])['Vehicle Mileage On Claim (km)'].mean()).reset_index(drop=False)
df_change

    Repairing Dealer State  Vehicle Mileage On Claim (km)
0             6000.0   NSW                  259371.976744
1             7830.0   NSW                  955105.000000
2            19053.0   VIC                  286386.529412
3            52589.0    SA                  425529.728972
4            70287.0    WA                  389137.345250
5            79129.0   VIC                  299036.382550
6            85993.0   QLD                  391024.361607
7            89508.0   NSW                  380593.894737
8            89540.0   QLD                  341847.531532
9            92197.0    SA                  385519.247372
10           92767.0    WA                  366155.711012
11           93351.0   QLD                  335866.394429
12           93385.0   NSW                  391717.898406
13          235191.0   NSW                  356586.838710
14          396485.0   VIC                  327629.242424
15          406291.0   QLD                  219375.809524
16          429723.0   VIC                  215961.615385
17          480274.0   NSW                  372007.847222
18          480277.0    TA                  330696.169231
19          482666.0   VIC                  405532.640000
20          488428.0   QLD                  408165.493548
21          490233.0   QLD                  403913.875000
22          501207.0   NSW                  297411.655172
23          511728.0   NSW                  346510.677966
24          542457.0    WA                  375488.112310
25          542468.0   QLD                  338630.333333
26          543517.0   QLD                  644975.375000
27          552993.0   VIC                  323237.320158
28          584693.0   NSW                  208510.166667
29          600828.0    SA                  336665.492830
30          601570.0    TA                  276822.662651
31          601571.0    SA                  291910.485222
32          601578.0    WA                  280269.721939
33          629286.0    WA                  238600.518519
34          629287.0   NSW                  201403.172566
35          630205.0    WA                  270134.513158
36          630207.0   QLD                  359523.734940
37          630208.0   NSW                  335178.205882
38          631891.0    TA                  247014.073529
39          688845.0   NSW                  150839.250000
40          691188.0    SA                  383622.946934
41          698302.0   NSW                  417827.000000
42          704541.0   VIC                  213453.000000
43          742348.0    WA                  120008.000000
44          754615.0   QLD                   10358.000000
45          756048.0    SA                  167744.666667
46          762478.0   NSW                  370307.683673
47          766085.0   NSW                  421009.916143
48          788051.0   NSW                  318881.737864
49          880625.0   VIC                  359426.752044

In [27]:
#不同state卖哪些车型
df_stty = pd.DataFrame(df.groupby(['State'])['Vehicle Marketing Type'].apply(list)).reset_index(drop=False)
df_stty

  State                             Vehicle Marketing Type
0   NSW  [FH13 64T, FH13 64T, FH13 64T, FH13 64T, FH13 ...
1   QLD  [FH13 64T, FH13 64T, FH13 64T, FH13 64T, FH13A...
2    SA  [FH13 64T, FH13 64T, FH13 64T, FEE7 64R, FH13 ...
3    TA  [FES7 62R, FH13 64T, FH13 64T, FM11 64T, FM11 ...
4   VIC  [FH13 64T, FH13 64T, FH13A64T, FH13A64T, FES7 ...
5    WA  [FH13 64T, FH13 64T, FH13 64T, FH13 64T, FH13 ...

In [28]:
#unique的车型
df_stty = pd.DataFrame(df.groupby(['State'])['Vehicle Marketing Type'].apply(set)).reset_index(drop=False)
df_stty

  State                             Vehicle Marketing Type
0   NSW  {FH13 84T, FM9  64R, FM13 64T, FH16 84T, FH16A...
1   QLD  {FM9  64R, FM13 64T, FH16 84T, FH16A84T, FM13 ...
2    SA  {FLM7 42D, FH13 84T, FM9  64R, FM13 64T, FH16 ...
3    TA  {FES7 62R, FH13A64T, FM9  84R, FLL7 42D, FM11 ...
4   VIC  {FM9  64R, FM13 64T, FH16 84T, FH16A84T, FM13 ...
5    WA  {FLM7 42D, FM11104R, FH13 84T, FM9  64R, FM13 ...

In [29]:
#13.分析credit card数据

In [30]:
#13.1 是topup的数据
df = pd.read_csv(r'datasets/topup_check.csv')
df[:5]

,Card,Merchant,Merchant Industry,Industry Description,Date,Trans Amt,Balance
0,1001,NaN,7841,Antique Reproductions,02/03/12 06:02:32,6.83,4778.00
1,1001,NaN,5451,"Watch, Clock, Jewelry, and Silverware Stores",02/03/12 06:03:20,66.80,4711.20
2,1001,NaN,8241,"Recreational and Utility Trailers, Camp Dealers",02/03/12 06:05:15,13.69,4697.51
3,1001,NaN,8734,Telecommunication service including local and ...,02/03/12 06:12:42,0.89,4696.62
4,1001,NaN,5399,Motor Home Dealers,02/03/12 06:13:41,191.25,4505.37

In [32]:
df['Prev_Bal'] = df['Balance'].shift(1)
df['Prev_Bal'].fillna(0,inplace=True)
df['Prev_Crd'] = df['Card'].shift(1)
df['Prev_Crd'].fillna(0,inplace=True)
df['Topup'] = df.apply(lambda row: True if row['Balance'] > row['Prev_Bal'] and row['Trans Amt']>0 \
                       and row['Card'] == row['Prev_Crd'] else False, axis=1)
df

/var/folders/bv/dtsl2dms55b8p7r8cf91tk_r0000gn/T/ipykernel_80519/3482830710.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Prev_Bal'].fillna(0,inplace=True)
/var/folders/bv/dtsl2dms55b8p7r8cf91tk_r0000gn/T/ipykernel_80519/3482830710.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Prev_Crd'].fillna(0,inplace=True)

,Card,Merchant,Merchant Industry,Industry Description,Date,Trans Amt,Balance,Prev_Bal,Prev_Crd,Topup
0,1001,NaN,7841,Antique Reproductions,02/03/12 06:02:32,6.83,4778.00,0.00,0.0,False
1,1001,NaN,5451,"Watch, Clock, Jewelry, and Silverware Stores",02/03/12 06:03:20,66.80,4711.20,4778.00,1001.0,False
2,1001,NaN,8241,"Recreational and Utility Trailers, Camp Dealers",02/03/12 06:05:15,13.69,4697.51,4711.20,1001.0,False
3,1001,NaN,8734,Telecommunication service including local and ...,02/03/12 06:12:42,0.89,4696.62,4697.51,1001.0,False
4,1001,NaN,5399,Motor Home Dealers,02/03/12 06:13:41,191.25,4505.37,4696.62,1001.0,False
...,...,...,...,...,...,...,...,...,...,...
265,1011,NaN,5231,Door - to - Door Sales,02/03/12 08:05:39,23.49,129.05,141.55,1011.0,False
266,1011,NaN,5533,"Florists’ Supplies, Nursery Stock and Flowers",02/03/12 08:10:21,0.00,105.56,129.05,1011.0,False
267,1011,NaN,7699,Caterers,02/03/12 08:13:48,4.49,105.56,105.56,1011.0,False
268,1011,NaN,6011,"Insurance Premiums, (no longer valid for first...",02/03/12 08:14:36,1.29,101.07,105.56,1011.0,False
269,1011,NaN,8011,"Drugs, Drug Proprietors, and Druggist’s Sundries",02/03/12 08:16:28,129.21,99.78,101.07,1011.0,False

In [40]:
#13.2 分析entropy

In [39]:
pip install scipy

Collecting scipy
  Downloading scipy-1.14.1-cp312-cp312-macosx_14_0_arm64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 6.3 MB/s eta 0:00:00
Requirement already satisfied: numpy<2.3,>=1.23.5 in ./myenv/lib/python3.12/site-packages (from scipy) (2.1.2)
Downloading scipy-1.14.1-cp312-cp312-macosx_14_0_arm64.whl (23.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/23.1 MB 12.8 MB/s eta 0:00:0000:0100:01
Installing collected packages: scipy
Successfully installed scipy-1.14.1

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [41]:
import scipy.stats

def calculate_ent(ary):
    p_data = ary.value_counts()
    entrophy = scipy.stats.entropy(p_data)
    return entrophy

In [42]:
df_ent = pd.DataFrame(df.groupby(['Card'])['Merchant Industry'].apply(calculate_ent)).reset_index(drop=False)
df_ent

    Card  Merchant Industry
0   1001           3.308778
1   1002           2.890372
2   1003           3.131334
3   1004           3.354988
4   1005           3.282694
5   1006           3.233183
6   1007           3.233183
7   1008           2.995732
8   1009           2.615631
9   1010           2.926418
10  1011           3.193148